static const uint16_t node_u1100u1100_jamo_seq[] = {
	0x1100,
	0x1100,
};
static const struct Node node_u1100u1100 = {
	83,
	2,
	node_u1100u1100_jamo_seq,
	0x1100,
	0x1101,
	0,
	0,
	"u1100u1100",
};
static const uint16_t node_u1100u1103_jamo_seq[] = {
	0x1100,
	0x1103,
};
static const struct Node node_u1100u1103 = {
	84,
	2,
	node_u1100u1103_jamo_seq,
	0x1103,
	0x115a,
	0,
	0,
	"u1100u1103",
};
static const struct Node *node_u1100_children[] = {
	&node_u1100u1100,
	&node_u1100u1103,
};
static const uint16_t node_u1100_jamo_seq[] = {
	0x1100,
};
static const struct Node node_u1100 = {
	1,
	1,
	node_u1100_jamo_seq,
	0x1100,
	0,
	2,
	node_u1100_children,
	"u1100",
};
static const uint16_t node_u1102u1100_jamo_seq[] = {
	0x1102,
	0x1100,
};
static const struct Node node_u1102u1100 = {
	85,
	2,
	node_u1102u1100_jamo_seq,
	0x1100,
	0x1113,
	0,
	0,
	"u1102u1100",
};
static const uint16_t node_u1102u1102_jamo_seq[] = {
	0x1102,
	0x1102,
};
static const struct Node node_u1102u1102 = {
	86,
	2,
	node_u1102u1102_jamo_seq,
	0x1102,
	0x1114,
	0,
	0,
	"u1102u1102",
};
static const uint16_t node_u1102u1103_jamo_seq[] = {
	0x1102,
	0x1103,
};
static const struct Node node_u1102u1103 = {
	87,
	2,
	node_u1102u1103_jamo_seq,
	0x1103,
	0x1115,
	0,
	0,
	"u1102u1103",
};
static const uint16_t node_u1102u1107_jamo_seq[] = {
	0x1102,
	0x1107,
};
static const struct Node node_u1102u1107 = {
	88,
	2,
	node_u1102u1107_jamo_seq,
	0x1107,
	0x1116,
	0,
	0,
	"u1102u1107",
};
static const uint16_t node_u1102u1109_jamo_seq[] = {
	0x1102,
	0x1109,
};
static const struct Node node_u1102u1109 = {
	89,
	2,
	node_u1102u1109_jamo_seq,
	0x1109,
	0x115b,
	0,
	0,
	"u1102u1109",
};
static const uint16_t node_u1102u110c_jamo_seq[] = {
	0x1102,
	0x110c,
};
static const struct Node node_u1102u110c = {
	90,
	2,
	node_u1102u110c_jamo_seq,
	0x110c,
	0x115c,
	0,
	0,
	"u1102u110c",
};
static const uint16_t node_u1102u1112_jamo_seq[] = {
	0x1102,
	0x1112,
};
static const struct Node node_u1102u1112 = {
	91,
	2,
	node_u1102u1112_jamo_seq,
	0x1112,
	0x115d,
	0,
	0,
	"u1102u1112",
};
static const struct Node *node_u1102_children[] = {
	&node_u1102u1100,
	&node_u1102u1102,
	&node_u1102u1103,
	&node_u1102u1107,
	&node_u1102u1109,
	&node_u1102u110c,
	&node_u1102u1112,
};
static const uint16_t node_u1102_jamo_seq[] = {
	0x1102,
};
static const struct Node node_u1102 = {
	2,
	1,
	node_u1102_jamo_seq,
	0x1102,
	0,
	7,
	node_u1102_children,
	"u1102",
};
static const uint16_t node_u1103u1100_jamo_seq[] = {
	0x1103,
	0x1100,
};
static const struct Node node_u1103u1100 = {
	92,
	2,
	node_u1103u1100_jamo_seq,
	0x1100,
	0x1117,
	0,
	0,
	"u1103u1100",
};
static const uint16_t node_u1103u1103_jamo_seq[] = {
	0x1103,
	0x1103,
};
static const struct Node node_u1103u1103 = {
	93,
	2,
	node_u1103u1103_jamo_seq,
	0x1103,
	0x1104,
	0,
	0,
	"u1103u1103",
};
static const uint16_t node_u1103u1105_jamo_seq[] = {
	0x1103,
	0x1105,
};
static const struct Node node_u1103u1105 = {
	94,
	2,
	node_u1103u1105_jamo_seq,
	0x1105,
	0x115e,
	0,
	0,
	"u1103u1105",
};
static const uint16_t node_u1103u1106_jamo_seq[] = {
	0x1103,
	0x1106,
};
static const struct Node node_u1103u1106 = {
	95,
	2,
	node_u1103u1106_jamo_seq,
	0x1106,
	0xa960,
	0,
	0,
	"u1103u1106",
};
static const uint16_t node_u1103u1107_jamo_seq[] = {
	0x1103,
	0x1107,
};
static const struct Node node_u1103u1107 = {
	96,
	2,
	node_u1103u1107_jamo_seq,
	0x1107,
	0xa961,
	0,
	0,
	"u1103u1107",
};
static const uint16_t node_u1103u1109_jamo_seq[] = {
	0x1103,
	0x1109,
};
static const struct Node node_u1103u1109 = {
	97,
	2,
	node_u1103u1109_jamo_seq,
	0x1109,
	0xa962,
	0,
	0,
	"u1103u1109",
};
static const uint16_t node_u1103u110c_jamo_seq[] = {
	0x1103,
	0x110c,
};
static const struct Node node_u1103u110c = {
	98,
	2,
	node_u1103u110c_jamo_seq,
	0x110c,
	0xa963,
	0,
	0,
	"u1103u110c",
};
static const struct Node *node_u1103_children[] = {
	&node_u1103u1100,
	&node_u1103u1103,
	&node_u1103u1105,
	&node_u1103u1106,
	&node_u1103u1107,
	&node_u1103u1109,
	&node_u1103u110c,
};
static const uint16_t node_u1103_jamo_seq[] = {
	0x1103,
};
static const struct Node node_u1103 = {
	3,
	1,
	node_u1103_jamo_seq,
	0x1103,
	0,
	7,
	node_u1103_children,
	"u1103",
};
static const uint16_t node_u1105u1100u1100_jamo_seq[] = {
	0x1105,
	0x1100,
	0x1100,
};
static const struct Node node_u1105u1100u1100 = {
	444,
	3,
	node_u1105u1100u1100_jamo_seq,
	0x1100,
	0xa965,
	0,
	0,
	"u1105u1100u1100",
};
static const struct Node *node_u1105u1100_children[] = {
	&node_u1105u1100u1100,
};
static const uint16_t node_u1105u1100_jamo_seq[] = {
	0x1105,
	0x1100,
};
static const struct Node node_u1105u1100 = {
	99,
	2,
	node_u1105u1100_jamo_seq,
	0x1100,
	0xa964,
	1,
	node_u1105u1100_children,
	"u1105u1100",
};
static const uint16_t node_u1105u1101_jamo_seq[] = {
	0x1105,
	0x1101,
};
static const struct Node node_u1105u1101 = {
	100,
	2,
	node_u1105u1101_jamo_seq,
	0x1101,
	0xa965,
	0,
	0,
	"u1105u1101",
};
static const uint16_t node_u1105u1102_jamo_seq[] = {
	0x1105,
	0x1102,
};
static const struct Node node_u1105u1102 = {
	101,
	2,
	node_u1105u1102_jamo_seq,
	0x1102,
	0x1118,
	0,
	0,
	"u1105u1102",
};
static const uint16_t node_u1105u1103u1103_jamo_seq[] = {
	0x1105,
	0x1103,
	0x1103,
};
static const struct Node node_u1105u1103u1103 = {
	445,
	3,
	node_u1105u1103u1103_jamo_seq,
	0x1103,
	0xa967,
	0,
	0,
	"u1105u1103u1103",
};
static const struct Node *node_u1105u1103_children[] = {
	&node_u1105u1103u1103,
};
static const uint16_t node_u1105u1103_jamo_seq[] = {
	0x1105,
	0x1103,
};
static const struct Node node_u1105u1103 = {
	102,
	2,
	node_u1105u1103_jamo_seq,
	0x1103,
	0xa966,
	1,
	node_u1105u1103_children,
	"u1105u1103",
};
static const uint16_t node_u1105u1104_jamo_seq[] = {
	0x1105,
	0x1104,
};
static const struct Node node_u1105u1104 = {
	103,
	2,
	node_u1105u1104_jamo_seq,
	0x1104,
	0xa967,
	0,
	0,
	"u1105u1104",
};
static const uint16_t node_u1105u1105_jamo_seq[] = {
	0x1105,
	0x1105,
};
static const struct Node node_u1105u1105 = {
	104,
	2,
	node_u1105u1105_jamo_seq,
	0x1105,
	0x1119,
	0,
	0,
	"u1105u1105",
};
static const uint16_t node_u1105u1106_jamo_seq[] = {
	0x1105,
	0x1106,
};
static const struct Node node_u1105u1106 = {
	105,
	2,
	node_u1105u1106_jamo_seq,
	0x1106,
	0xa968,
	0,
	0,
	"u1105u1106",
};
static const uint16_t node_u1105u1107u1107_jamo_seq[] = {
	0x1105,
	0x1107,
	0x1107,
};
static const struct Node node_u1105u1107u1107 = {
	446,
	3,
	node_u1105u1107u1107_jamo_seq,
	0x1107,
	0xa96a,
	0,
	0,
	"u1105u1107u1107",
};
static const uint16_t node_u1105u1107u110b_jamo_seq[] = {
	0x1105,
	0x1107,
	0x110b,
};
static const struct Node node_u1105u1107u110b = {
	447,
	3,
	node_u1105u1107u110b_jamo_seq,
	0x110b,
	0xa96b,
	0,
	0,
	"u1105u1107u110b",
};
static const struct Node *node_u1105u1107_children[] = {
	&node_u1105u1107u1107,
	&node_u1105u1107u110b,
};
static const uint16_t node_u1105u1107_jamo_seq[] = {
	0x1105,
	0x1107,
};
static const struct Node node_u1105u1107 = {
	106,
	2,
	node_u1105u1107_jamo_seq,
	0x1107,
	0xa969,
	2,
	node_u1105u1107_children,
	"u1105u1107",
};
static const uint16_t node_u1105u1108_jamo_seq[] = {
	0x1105,
	0x1108,
};
static const struct Node node_u1105u1108 = {
	107,
	2,
	node_u1105u1108_jamo_seq,
	0x1108,
	0xa96a,
	0,
	0,
	"u1105u1108",
};
static const uint16_t node_u1105u1109_jamo_seq[] = {
	0x1105,
	0x1109,
};
static const struct Node node_u1105u1109 = {
	108,
	2,
	node_u1105u1109_jamo_seq,
	0x1109,
	0xa96c,
	0,
	0,
	"u1105u1109",
};
static const uint16_t node_u1105u110b_jamo_seq[] = {
	0x1105,
	0x110b,
};
static const struct Node node_u1105u110b = {
	109,
	2,
	node_u1105u110b_jamo_seq,
	0x110b,
	0x111b,
	0,
	0,
	"u1105u110b",
};
static const uint16_t node_u1105u110c_jamo_seq[] = {
	0x1105,
	0x110c,
};
static const struct Node node_u1105u110c = {
	110,
	2,
	node_u1105u110c_jamo_seq,
	0x110c,
	0xa96d,
	0,
	0,
	"u1105u110c",
};
static const uint16_t node_u1105u110f_jamo_seq[] = {
	0x1105,
	0x110f,
};
static const struct Node node_u1105u110f = {
	111,
	2,
	node_u1105u110f_jamo_seq,
	0x110f,
	0xa96e,
	0,
	0,
	"u1105u110f",
};
static const uint16_t node_u1105u1112_jamo_seq[] = {
	0x1105,
	0x1112,
};
static const struct Node node_u1105u1112 = {
	112,
	2,
	node_u1105u1112_jamo_seq,
	0x1112,
	0x111a,
	0,
	0,
	"u1105u1112",
};
static const uint16_t node_u1105u112b_jamo_seq[] = {
	0x1105,
	0x112b,
};
static const struct Node node_u1105u112b = {
	113,
	2,
	node_u1105u112b_jamo_seq,
	0x112b,
	0xa96b,
	0,
	0,
	"u1105u112b",
};
static const struct Node *node_u1105_children[] = {
	&node_u1105u1100,
	&node_u1105u1101,
	&node_u1105u1102,
	&node_u1105u1103,
	&node_u1105u1104,
	&node_u1105u1105,
	&node_u1105u1106,
	&node_u1105u1107,
	&node_u1105u1108,
	&node_u1105u1109,
	&node_u1105u110b,
	&node_u1105u110c,
	&node_u1105u110f,
	&node_u1105u1112,
	&node_u1105u112b,
};
static const uint16_t node_u1105_jamo_seq[] = {
	0x1105,
};
static const struct Node node_u1105 = {
	4,
	1,
	node_u1105_jamo_seq,
	0x1105,
	0,
	15,
	node_u1105_children,
	"u1105",
};
static const uint16_t node_u1106u1100_jamo_seq[] = {
	0x1106,
	0x1100,
};
static const struct Node node_u1106u1100 = {
	114,
	2,
	node_u1106u1100_jamo_seq,
	0x1100,
	0xa96f,
	0,
	0,
	"u1106u1100",
};
static const uint16_t node_u1106u1103_jamo_seq[] = {
	0x1106,
	0x1103,
};
static const struct Node node_u1106u1103 = {
	115,
	2,
	node_u1106u1103_jamo_seq,
	0x1103,
	0xa970,
	0,
	0,
	"u1106u1103",
};
static const uint16_t node_u1106u1107_jamo_seq[] = {
	0x1106,
	0x1107,
};
static const struct Node node_u1106u1107 = {
	116,
	2,
	node_u1106u1107_jamo_seq,
	0x1107,
	0x111c,
	0,
	0,
	"u1106u1107",
};
static const uint16_t node_u1106u1109_jamo_seq[] = {
	0x1106,
	0x1109,
};
static const struct Node node_u1106u1109 = {
	117,
	2,
	node_u1106u1109_jamo_seq,
	0x1109,
	0xa971,
	0,
	0,
	"u1106u1109",
};
static const uint16_t node_u1106u110b_jamo_seq[] = {
	0x1106,
	0x110b,
};
static const struct Node node_u1106u110b = {
	118,
	2,
	node_u1106u110b_jamo_seq,
	0x110b,
	0x111d,
	0,
	0,
	"u1106u110b",
};
static const struct Node *node_u1106_children[] = {
	&node_u1106u1100,
	&node_u1106u1103,
	&node_u1106u1107,
	&node_u1106u1109,
	&node_u1106u110b,
};
static const uint16_t node_u1106_jamo_seq[] = {
	0x1106,
};
static const struct Node node_u1106 = {
	5,
	1,
	node_u1106_jamo_seq,
	0x1106,
	0,
	5,
	node_u1106_children,
	"u1106",
};
static const uint16_t node_u1107u1100_jamo_seq[] = {
	0x1107,
	0x1100,
};
static const struct Node node_u1107u1100 = {
	119,
	2,
	node_u1107u1100_jamo_seq,
	0x1100,
	0x111e,
	0,
	0,
	"u1107u1100",
};
static const uint16_t node_u1107u1102_jamo_seq[] = {
	0x1107,
	0x1102,
};
static const struct Node node_u1107u1102 = {
	120,
	2,
	node_u1107u1102_jamo_seq,
	0x1102,
	0x111f,
	0,
	0,
	"u1107u1102",
};
static const uint16_t node_u1107u1103_jamo_seq[] = {
	0x1107,
	0x1103,
};
static const struct Node node_u1107u1103 = {
	121,
	2,
	node_u1107u1103_jamo_seq,
	0x1103,
	0x1120,
	0,
	0,
	"u1107u1103",
};
static const uint16_t node_u1107u1107u110b_jamo_seq[] = {
	0x1107,
	0x1107,
	0x110b,
};
static const struct Node node_u1107u1107u110b = {
	448,
	3,
	node_u1107u1107u110b_jamo_seq,
	0x110b,
	0x112c,
	0,
	0,
	"u1107u1107u110b",
};
static const struct Node *node_u1107u1107_children[] = {
	&node_u1107u1107u110b,
};
static const uint16_t node_u1107u1107_jamo_seq[] = {
	0x1107,
	0x1107,
};
static const struct Node node_u1107u1107 = {
	122,
	2,
	node_u1107u1107_jamo_seq,
	0x1107,
	0x1108,
	1,
	node_u1107u1107_children,
	"u1107u1107",
};
static const uint16_t node_u1107u1109u1100_jamo_seq[] = {
	0x1107,
	0x1109,
	0x1100,
};
static const struct Node node_u1107u1109u1100 = {
	449,
	3,
	node_u1107u1109u1100_jamo_seq,
	0x1100,
	0x1122,
	0,
	0,
	"u1107u1109u1100",
};
static const uint16_t node_u1107u1109u1103_jamo_seq[] = {
	0x1107,
	0x1109,
	0x1103,
};
static const struct Node node_u1107u1109u1103 = {
	450,
	3,
	node_u1107u1109u1103_jamo_seq,
	0x1103,
	0x1123,
	0,
	0,
	"u1107u1109u1103",
};
static const uint16_t node_u1107u1109u1107_jamo_seq[] = {
	0x1107,
	0x1109,
	0x1107,
};
static const struct Node node_u1107u1109u1107 = {
	451,
	3,
	node_u1107u1109u1107_jamo_seq,
	0x1107,
	0x1124,
	0,
	0,
	"u1107u1109u1107",
};
static const uint16_t node_u1107u1109u1109_jamo_seq[] = {
	0x1107,
	0x1109,
	0x1109,
};
static const struct Node node_u1107u1109u1109 = {
	452,
	3,
	node_u1107u1109u1109_jamo_seq,
	0x1109,
	0x1125,
	0,
	0,
	"u1107u1109u1109",
};
static const uint16_t node_u1107u1109u110c_jamo_seq[] = {
	0x1107,
	0x1109,
	0x110c,
};
static const struct Node node_u1107u1109u110c = {
	453,
	3,
	node_u1107u1109u110c_jamo_seq,
	0x110c,
	0x1126,
	0,
	0,
	"u1107u1109u110c",
};
static const uint16_t node_u1107u1109u1110_jamo_seq[] = {
	0x1107,
	0x1109,
	0x1110,
};
static const struct Node node_u1107u1109u1110 = {
	454,
	3,
	node_u1107u1109u1110_jamo_seq,
	0x1110,
	0xa972,
	0,
	0,
	"u1107u1109u1110",
};
static const struct Node *node_u1107u1109_children[] = {
	&node_u1107u1109u1100,
	&node_u1107u1109u1103,
	&node_u1107u1109u1107,
	&node_u1107u1109u1109,
	&node_u1107u1109u110c,
	&node_u1107u1109u1110,
};
static const uint16_t node_u1107u1109_jamo_seq[] = {
	0x1107,
	0x1109,
};
static const struct Node node_u1107u1109 = {
	123,
	2,
	node_u1107u1109_jamo_seq,
	0x1109,
	0x1121,
	6,
	node_u1107u1109_children,
	"u1107u1109",
};
static const uint16_t node_u1107u110a_jamo_seq[] = {
	0x1107,
	0x110a,
};
static const struct Node node_u1107u110a = {
	124,
	2,
	node_u1107u110a_jamo_seq,
	0x110a,
	0x1125,
	0,
	0,
	"u1107u110a",
};
static const uint16_t node_u1107u110b_jamo_seq[] = {
	0x1107,
	0x110b,
};
static const struct Node node_u1107u110b = {
	125,
	2,
	node_u1107u110b_jamo_seq,
	0x110b,
	0x112b,
	0,
	0,
	"u1107u110b",
};
static const uint16_t node_u1107u110c_jamo_seq[] = {
	0x1107,
	0x110c,
};
static const struct Node node_u1107u110c = {
	126,
	2,
	node_u1107u110c_jamo_seq,
	0x110c,
	0x1127,
	0,
	0,
	"u1107u110c",
};
static const uint16_t node_u1107u110e_jamo_seq[] = {
	0x1107,
	0x110e,
};
static const struct Node node_u1107u110e = {
	127,
	2,
	node_u1107u110e_jamo_seq,
	0x110e,
	0x1128,
	0,
	0,
	"u1107u110e",
};
static const uint16_t node_u1107u110f_jamo_seq[] = {
	0x1107,
	0x110f,
};
static const struct Node node_u1107u110f = {
	128,
	2,
	node_u1107u110f_jamo_seq,
	0x110f,
	0xa973,
	0,
	0,
	"u1107u110f",
};
static const uint16_t node_u1107u1110_jamo_seq[] = {
	0x1107,
	0x1110,
};
static const struct Node node_u1107u1110 = {
	129,
	2,
	node_u1107u1110_jamo_seq,
	0x1110,
	0x1129,
	0,
	0,
	"u1107u1110",
};
static const uint16_t node_u1107u1111_jamo_seq[] = {
	0x1107,
	0x1111,
};
static const struct Node node_u1107u1111 = {
	130,
	2,
	node_u1107u1111_jamo_seq,
	0x1111,
	0x112a,
	0,
	0,
	"u1107u1111",
};
static const uint16_t node_u1107u1112_jamo_seq[] = {
	0x1107,
	0x1112,
};
static const struct Node node_u1107u1112 = {
	131,
	2,
	node_u1107u1112_jamo_seq,
	0x1112,
	0xa974,
	0,
	0,
	"u1107u1112",
};
static const uint16_t node_u1107u112b_jamo_seq[] = {
	0x1107,
	0x112b,
};
static const struct Node node_u1107u112b = {
	132,
	2,
	node_u1107u112b_jamo_seq,
	0x112b,
	0x112c,
	0,
	0,
	"u1107u112b",
};
static const uint16_t node_u1107u112d_jamo_seq[] = {
	0x1107,
	0x112d,
};
static const struct Node node_u1107u112d = {
	133,
	2,
	node_u1107u112d_jamo_seq,
	0x112d,
	0x1122,
	0,
	0,
	"u1107u112d",
};
static const uint16_t node_u1107u112f_jamo_seq[] = {
	0x1107,
	0x112f,
};
static const struct Node node_u1107u112f = {
	134,
	2,
	node_u1107u112f_jamo_seq,
	0x112f,
	0x1123,
	0,
	0,
	"u1107u112f",
};
static const uint16_t node_u1107u1132_jamo_seq[] = {
	0x1107,
	0x1132,
};
static const struct Node node_u1107u1132 = {
	135,
	2,
	node_u1107u1132_jamo_seq,
	0x1132,
	0x1124,
	0,
	0,
	"u1107u1132",
};
static const uint16_t node_u1107u1136_jamo_seq[] = {
	0x1107,
	0x1136,
};
static const struct Node node_u1107u1136 = {
	136,
	2,
	node_u1107u1136_jamo_seq,
	0x1136,
	0x1126,
	0,
	0,
	"u1107u1136",
};
static const uint16_t node_u1107u1139_jamo_seq[] = {
	0x1107,
	0x1139,
};
static const struct Node node_u1107u1139 = {
	137,
	2,
	node_u1107u1139_jamo_seq,
	0x1139,
	0xa972,
	0,
	0,
	"u1107u1139",
};
static const struct Node *node_u1107_children[] = {
	&node_u1107u1100,
	&node_u1107u1102,
	&node_u1107u1103,
	&node_u1107u1107,
	&node_u1107u1109,
	&node_u1107u110a,
	&node_u1107u110b,
	&node_u1107u110c,
	&node_u1107u110e,
	&node_u1107u110f,
	&node_u1107u1110,
	&node_u1107u1111,
	&node_u1107u1112,
	&node_u1107u112b,
	&node_u1107u112d,
	&node_u1107u112f,
	&node_u1107u1132,
	&node_u1107u1136,
	&node_u1107u1139,
};
static const uint16_t node_u1107_jamo_seq[] = {
	0x1107,
};
static const struct Node node_u1107 = {
	6,
	1,
	node_u1107_jamo_seq,
	0x1107,
	0,
	19,
	node_u1107_children,
	"u1107",
};
static const uint16_t node_u1108u110b_jamo_seq[] = {
	0x1108,
	0x110b,
};
static const struct Node node_u1108u110b = {
	138,
	2,
	node_u1108u110b_jamo_seq,
	0x110b,
	0x112c,
	0,
	0,
	"u1108u110b",
};
static const struct Node *node_u1108_children[] = {
	&node_u1108u110b,
};
static const uint16_t node_u1108_jamo_seq[] = {
	0x1108,
};
static const struct Node node_u1108 = {
	7,
	1,
	node_u1108_jamo_seq,
	0x1108,
	0,
	1,
	node_u1108_children,
	"u1108",
};
static const uint16_t node_u1109u1100_jamo_seq[] = {
	0x1109,
	0x1100,
};
static const struct Node node_u1109u1100 = {
	139,
	2,
	node_u1109u1100_jamo_seq,
	0x1100,
	0x112d,
	0,
	0,
	"u1109u1100",
};
static const uint16_t node_u1109u1102_jamo_seq[] = {
	0x1109,
	0x1102,
};
static const struct Node node_u1109u1102 = {
	140,
	2,
	node_u1109u1102_jamo_seq,
	0x1102,
	0x112e,
	0,
	0,
	"u1109u1102",
};
static const uint16_t node_u1109u1103_jamo_seq[] = {
	0x1109,
	0x1103,
};
static const struct Node node_u1109u1103 = {
	141,
	2,
	node_u1109u1103_jamo_seq,
	0x1103,
	0x112f,
	0,
	0,
	"u1109u1103",
};
static const uint16_t node_u1109u1105_jamo_seq[] = {
	0x1109,
	0x1105,
};
static const struct Node node_u1109u1105 = {
	142,
	2,
	node_u1109u1105_jamo_seq,
	0x1105,
	0x1130,
	0,
	0,
	"u1109u1105",
};
static const uint16_t node_u1109u1106_jamo_seq[] = {
	0x1109,
	0x1106,
};
static const struct Node node_u1109u1106 = {
	143,
	2,
	node_u1109u1106_jamo_seq,
	0x1106,
	0x1131,
	0,
	0,
	"u1109u1106",
};
static const uint16_t node_u1109u1107u1100_jamo_seq[] = {
	0x1109,
	0x1107,
	0x1100,
};
static const struct Node node_u1109u1107u1100 = {
	455,
	3,
	node_u1109u1107u1100_jamo_seq,
	0x1100,
	0x1133,
	0,
	0,
	"u1109u1107u1100",
};
static const struct Node *node_u1109u1107_children[] = {
	&node_u1109u1107u1100,
};
static const uint16_t node_u1109u1107_jamo_seq[] = {
	0x1109,
	0x1107,
};
static const struct Node node_u1109u1107 = {
	144,
	2,
	node_u1109u1107_jamo_seq,
	0x1107,
	0x1132,
	1,
	node_u1109u1107_children,
	"u1109u1107",
};
static const uint16_t node_u1109u1109u1107_jamo_seq[] = {
	0x1109,
	0x1109,
	0x1107,
};
static const struct Node node_u1109u1109u1107 = {
	456,
	3,
	node_u1109u1109u1107_jamo_seq,
	0x1107,
	0xa975,
	0,
	0,
	"u1109u1109u1107",
};
static const uint16_t node_u1109u1109u1109_jamo_seq[] = {
	0x1109,
	0x1109,
	0x1109,
};
static const struct Node node_u1109u1109u1109 = {
	457,
	3,
	node_u1109u1109u1109_jamo_seq,
	0x1109,
	0x1134,
	0,
	0,
	"u1109u1109u1109",
};
static const struct Node *node_u1109u1109_children[] = {
	&node_u1109u1109u1107,
	&node_u1109u1109u1109,
};
static const uint16_t node_u1109u1109_jamo_seq[] = {
	0x1109,
	0x1109,
};
static const struct Node node_u1109u1109 = {
	145,
	2,
	node_u1109u1109_jamo_seq,
	0x1109,
	0x110a,
	2,
	node_u1109u1109_children,
	"u1109u1109",
};
static const uint16_t node_u1109u110a_jamo_seq[] = {
	0x1109,
	0x110a,
};
static const struct Node node_u1109u110a = {
	146,
	2,
	node_u1109u110a_jamo_seq,
	0x110a,
	0x1134,
	0,
	0,
	"u1109u110a",
};
static const uint16_t node_u1109u110b_jamo_seq[] = {
	0x1109,
	0x110b,
};
static const struct Node node_u1109u110b = {
	147,
	2,
	node_u1109u110b_jamo_seq,
	0x110b,
	0x1135,
	0,
	0,
	"u1109u110b",
};
static const uint16_t node_u1109u110c_jamo_seq[] = {
	0x1109,
	0x110c,
};
static const struct Node node_u1109u110c = {
	148,
	2,
	node_u1109u110c_jamo_seq,
	0x110c,
	0x1136,
	0,
	0,
	"u1109u110c",
};
static const uint16_t node_u1109u110e_jamo_seq[] = {
	0x1109,
	0x110e,
};
static const struct Node node_u1109u110e = {
	149,
	2,
	node_u1109u110e_jamo_seq,
	0x110e,
	0x1137,
	0,
	0,
	"u1109u110e",
};
static const uint16_t node_u1109u110f_jamo_seq[] = {
	0x1109,
	0x110f,
};
static const struct Node node_u1109u110f = {
	150,
	2,
	node_u1109u110f_jamo_seq,
	0x110f,
	0x1138,
	0,
	0,
	"u1109u110f",
};
static const uint16_t node_u1109u1110_jamo_seq[] = {
	0x1109,
	0x1110,
};
static const struct Node node_u1109u1110 = {
	151,
	2,
	node_u1109u1110_jamo_seq,
	0x1110,
	0x1139,
	0,
	0,
	"u1109u1110",
};
static const uint16_t node_u1109u1111_jamo_seq[] = {
	0x1109,
	0x1111,
};
static const struct Node node_u1109u1111 = {
	152,
	2,
	node_u1109u1111_jamo_seq,
	0x1111,
	0x113a,
	0,
	0,
	"u1109u1111",
};
static const uint16_t node_u1109u1112_jamo_seq[] = {
	0x1109,
	0x1112,
};
static const struct Node node_u1109u1112 = {
	153,
	2,
	node_u1109u1112_jamo_seq,
	0x1112,
	0x113b,
	0,
	0,
	"u1109u1112",
};
static const uint16_t node_u1109u111e_jamo_seq[] = {
	0x1109,
	0x111e,
};
static const struct Node node_u1109u111e = {
	154,
	2,
	node_u1109u111e_jamo_seq,
	0x111e,
	0x1133,
	0,
	0,
	"u1109u111e",
};
static const uint16_t node_u1109u1132_jamo_seq[] = {
	0x1109,
	0x1132,
};
static const struct Node node_u1109u1132 = {
	155,
	2,
	node_u1109u1132_jamo_seq,
	0x1132,
	0xa975,
	0,
	0,
	"u1109u1132",
};
static const struct Node *node_u1109_children[] = {
	&node_u1109u1100,
	&node_u1109u1102,
	&node_u1109u1103,
	&node_u1109u1105,
	&node_u1109u1106,
	&node_u1109u1107,
	&node_u1109u1109,
	&node_u1109u110a,
	&node_u1109u110b,
	&node_u1109u110c,
	&node_u1109u110e,
	&node_u1109u110f,
	&node_u1109u1110,
	&node_u1109u1111,
	&node_u1109u1112,
	&node_u1109u111e,
	&node_u1109u1132,
};
static const uint16_t node_u1109_jamo_seq[] = {
	0x1109,
};
static const struct Node node_u1109 = {
	8,
	1,
	node_u1109_jamo_seq,
	0x1109,
	0,
	17,
	node_u1109_children,
	"u1109",
};
static const uint16_t node_u110au1107_jamo_seq[] = {
	0x110a,
	0x1107,
};
static const struct Node node_u110au1107 = {
	156,
	2,
	node_u110au1107_jamo_seq,
	0x1107,
	0xa975,
	0,
	0,
	"u110au1107",
};
static const uint16_t node_u110au1109_jamo_seq[] = {
	0x110a,
	0x1109,
};
static const struct Node node_u110au1109 = {
	157,
	2,
	node_u110au1109_jamo_seq,
	0x1109,
	0x1134,
	0,
	0,
	"u110au1109",
};
static const struct Node *node_u110a_children[] = {
	&node_u110au1107,
	&node_u110au1109,
};
static const uint16_t node_u110a_jamo_seq[] = {
	0x110a,
};
static const struct Node node_u110a = {
	9,
	1,
	node_u110a_jamo_seq,
	0x110a,
	0,
	2,
	node_u110a_children,
	"u110a",
};
static const uint16_t node_u110bu1100_jamo_seq[] = {
	0x110b,
	0x1100,
};
static const struct Node node_u110bu1100 = {
	158,
	2,
	node_u110bu1100_jamo_seq,
	0x1100,
	0x1141,
	0,
	0,
	"u110bu1100",
};
static const uint16_t node_u110bu1103_jamo_seq[] = {
	0x110b,
	0x1103,
};
static const struct Node node_u110bu1103 = {
	159,
	2,
	node_u110bu1103_jamo_seq,
	0x1103,
	0x1142,
	0,
	0,
	"u110bu1103",
};
static const uint16_t node_u110bu1105_jamo_seq[] = {
	0x110b,
	0x1105,
};
static const struct Node node_u110bu1105 = {
	160,
	2,
	node_u110bu1105_jamo_seq,
	0x1105,
	0xa976,
	0,
	0,
	"u110bu1105",
};
static const uint16_t node_u110bu1106_jamo_seq[] = {
	0x110b,
	0x1106,
};
static const struct Node node_u110bu1106 = {
	161,
	2,
	node_u110bu1106_jamo_seq,
	0x1106,
	0x1143,
	0,
	0,
	"u110bu1106",
};
static const uint16_t node_u110bu1107_jamo_seq[] = {
	0x110b,
	0x1107,
};
static const struct Node node_u110bu1107 = {
	162,
	2,
	node_u110bu1107_jamo_seq,
	0x1107,
	0x1144,
	0,
	0,
	"u110bu1107",
};
static const uint16_t node_u110bu1109_jamo_seq[] = {
	0x110b,
	0x1109,
};
static const struct Node node_u110bu1109 = {
	163,
	2,
	node_u110bu1109_jamo_seq,
	0x1109,
	0x1145,
	0,
	0,
	"u110bu1109",
};
static const uint16_t node_u110bu110b_jamo_seq[] = {
	0x110b,
	0x110b,
};
static const struct Node node_u110bu110b = {
	164,
	2,
	node_u110bu110b_jamo_seq,
	0x110b,
	0x1147,
	0,
	0,
	"u110bu110b",
};
static const uint16_t node_u110bu110c_jamo_seq[] = {
	0x110b,
	0x110c,
};
static const struct Node node_u110bu110c = {
	165,
	2,
	node_u110bu110c_jamo_seq,
	0x110c,
	0x1148,
	0,
	0,
	"u110bu110c",
};
static const uint16_t node_u110bu110e_jamo_seq[] = {
	0x110b,
	0x110e,
};
static const struct Node node_u110bu110e = {
	166,
	2,
	node_u110bu110e_jamo_seq,
	0x110e,
	0x1149,
	0,
	0,
	"u110bu110e",
};
static const uint16_t node_u110bu1110_jamo_seq[] = {
	0x110b,
	0x1110,
};
static const struct Node node_u110bu1110 = {
	167,
	2,
	node_u110bu1110_jamo_seq,
	0x1110,
	0x114a,
	0,
	0,
	"u110bu1110",
};
static const uint16_t node_u110bu1111_jamo_seq[] = {
	0x110b,
	0x1111,
};
static const struct Node node_u110bu1111 = {
	168,
	2,
	node_u110bu1111_jamo_seq,
	0x1111,
	0x114b,
	0,
	0,
	"u110bu1111",
};
static const uint16_t node_u110bu1112_jamo_seq[] = {
	0x110b,
	0x1112,
};
static const struct Node node_u110bu1112 = {
	169,
	2,
	node_u110bu1112_jamo_seq,
	0x1112,
	0xa977,
	0,
	0,
	"u110bu1112",
};
static const uint16_t node_u110bu1140_jamo_seq[] = {
	0x110b,
	0x1140,
};
static const struct Node node_u110bu1140 = {
	170,
	2,
	node_u110bu1140_jamo_seq,
	0x1140,
	0x1146,
	0,
	0,
	"u110bu1140",
};
static const struct Node *node_u110b_children[] = {
	&node_u110bu1100,
	&node_u110bu1103,
	&node_u110bu1105,
	&node_u110bu1106,
	&node_u110bu1107,
	&node_u110bu1109,
	&node_u110bu110b,
	&node_u110bu110c,
	&node_u110bu110e,
	&node_u110bu1110,
	&node_u110bu1111,
	&node_u110bu1112,
	&node_u110bu1140,
};
static const uint16_t node_u110b_jamo_seq[] = {
	0x110b,
};
static const struct Node node_u110b = {
	10,
	1,
	node_u110b_jamo_seq,
	0x110b,
	0,
	13,
	node_u110b_children,
	"u110b",
};
static const uint16_t node_u110cu110b_jamo_seq[] = {
	0x110c,
	0x110b,
};
static const struct Node node_u110cu110b = {
	171,
	2,
	node_u110cu110b_jamo_seq,
	0x110b,
	0x114d,
	0,
	0,
	"u110cu110b",
};
static const uint16_t node_u110cu110cu1112_jamo_seq[] = {
	0x110c,
	0x110c,
	0x1112,
};
static const struct Node node_u110cu110cu1112 = {
	458,
	3,
	node_u110cu110cu1112_jamo_seq,
	0x1112,
	0xa978,
	0,
	0,
	"u110cu110cu1112",
};
static const struct Node *node_u110cu110c_children[] = {
	&node_u110cu110cu1112,
};
static const uint16_t node_u110cu110c_jamo_seq[] = {
	0x110c,
	0x110c,
};
static const struct Node node_u110cu110c = {
	172,
	2,
	node_u110cu110c_jamo_seq,
	0x110c,
	0x110d,
	1,
	node_u110cu110c_children,
	"u110cu110c",
};
static const struct Node *node_u110c_children[] = {
	&node_u110cu110b,
	&node_u110cu110c,
};
static const uint16_t node_u110c_jamo_seq[] = {
	0x110c,
};
static const struct Node node_u110c = {
	11,
	1,
	node_u110c_jamo_seq,
	0x110c,
	0,
	2,
	node_u110c_children,
	"u110c",
};
static const uint16_t node_u110du1112_jamo_seq[] = {
	0x110d,
	0x1112,
};
static const struct Node node_u110du1112 = {
	173,
	2,
	node_u110du1112_jamo_seq,
	0x1112,
	0xa978,
	0,
	0,
	"u110du1112",
};
static const struct Node *node_u110d_children[] = {
	&node_u110du1112,
};
static const uint16_t node_u110d_jamo_seq[] = {
	0x110d,
};
static const struct Node node_u110d = {
	12,
	1,
	node_u110d_jamo_seq,
	0x110d,
	0,
	1,
	node_u110d_children,
	"u110d",
};
static const uint16_t node_u110eu110f_jamo_seq[] = {
	0x110e,
	0x110f,
};
static const struct Node node_u110eu110f = {
	174,
	2,
	node_u110eu110f_jamo_seq,
	0x110f,
	0x1152,
	0,
	0,
	"u110eu110f",
};
static const uint16_t node_u110eu1112_jamo_seq[] = {
	0x110e,
	0x1112,
};
static const struct Node node_u110eu1112 = {
	175,
	2,
	node_u110eu1112_jamo_seq,
	0x1112,
	0x1153,
	0,
	0,
	"u110eu1112",
};
static const struct Node *node_u110e_children[] = {
	&node_u110eu110f,
	&node_u110eu1112,
};
static const uint16_t node_u110e_jamo_seq[] = {
	0x110e,
};
static const struct Node node_u110e = {
	13,
	1,
	node_u110e_jamo_seq,
	0x110e,
	0,
	2,
	node_u110e_children,
	"u110e",
};
static const uint16_t node_u1110u1110_jamo_seq[] = {
	0x1110,
	0x1110,
};
static const struct Node node_u1110u1110 = {
	176,
	2,
	node_u1110u1110_jamo_seq,
	0x1110,
	0xa979,
	0,
	0,
	"u1110u1110",
};
static const struct Node *node_u1110_children[] = {
	&node_u1110u1110,
};
static const uint16_t node_u1110_jamo_seq[] = {
	0x1110,
};
static const struct Node node_u1110 = {
	14,
	1,
	node_u1110_jamo_seq,
	0x1110,
	0,
	1,
	node_u1110_children,
	"u1110",
};
static const uint16_t node_u1111u1107_jamo_seq[] = {
	0x1111,
	0x1107,
};
static const struct Node node_u1111u1107 = {
	177,
	2,
	node_u1111u1107_jamo_seq,
	0x1107,
	0x1156,
	0,
	0,
	"u1111u1107",
};
static const uint16_t node_u1111u110b_jamo_seq[] = {
	0x1111,
	0x110b,
};
static const struct Node node_u1111u110b = {
	178,
	2,
	node_u1111u110b_jamo_seq,
	0x110b,
	0x1157,
	0,
	0,
	"u1111u110b",
};
static const uint16_t node_u1111u1112_jamo_seq[] = {
	0x1111,
	0x1112,
};
static const struct Node node_u1111u1112 = {
	179,
	2,
	node_u1111u1112_jamo_seq,
	0x1112,
	0xa97a,
	0,
	0,
	"u1111u1112",
};
static const struct Node *node_u1111_children[] = {
	&node_u1111u1107,
	&node_u1111u110b,
	&node_u1111u1112,
};
static const uint16_t node_u1111_jamo_seq[] = {
	0x1111,
};
static const struct Node node_u1111 = {
	15,
	1,
	node_u1111_jamo_seq,
	0x1111,
	0,
	3,
	node_u1111_children,
	"u1111",
};
static const uint16_t node_u1112u1109_jamo_seq[] = {
	0x1112,
	0x1109,
};
static const struct Node node_u1112u1109 = {
	180,
	2,
	node_u1112u1109_jamo_seq,
	0x1109,
	0xa97b,
	0,
	0,
	"u1112u1109",
};
static const uint16_t node_u1112u1112_jamo_seq[] = {
	0x1112,
	0x1112,
};
static const struct Node node_u1112u1112 = {
	181,
	2,
	node_u1112u1112_jamo_seq,
	0x1112,
	0x1158,
	0,
	0,
	"u1112u1112",
};
static const struct Node *node_u1112_children[] = {
	&node_u1112u1109,
	&node_u1112u1112,
};
static const uint16_t node_u1112_jamo_seq[] = {
	0x1112,
};
static const struct Node node_u1112 = {
	16,
	1,
	node_u1112_jamo_seq,
	0x1112,
	0,
	2,
	node_u1112_children,
	"u1112",
};
static const uint16_t node_u1121u1100_jamo_seq[] = {
	0x1121,
	0x1100,
};
static const struct Node node_u1121u1100 = {
	182,
	2,
	node_u1121u1100_jamo_seq,
	0x1100,
	0x1122,
	0,
	0,
	"u1121u1100",
};
static const uint16_t node_u1121u1103_jamo_seq[] = {
	0x1121,
	0x1103,
};
static const struct Node node_u1121u1103 = {
	183,
	2,
	node_u1121u1103_jamo_seq,
	0x1103,
	0x1123,
	0,
	0,
	"u1121u1103",
};
static const uint16_t node_u1121u1107_jamo_seq[] = {
	0x1121,
	0x1107,
};
static const struct Node node_u1121u1107 = {
	184,
	2,
	node_u1121u1107_jamo_seq,
	0x1107,
	0x1124,
	0,
	0,
	"u1121u1107",
};
static const uint16_t node_u1121u1109_jamo_seq[] = {
	0x1121,
	0x1109,
};
static const struct Node node_u1121u1109 = {
	185,
	2,
	node_u1121u1109_jamo_seq,
	0x1109,
	0x1125,
	0,
	0,
	"u1121u1109",
};
static const uint16_t node_u1121u110c_jamo_seq[] = {
	0x1121,
	0x110c,
};
static const struct Node node_u1121u110c = {
	186,
	2,
	node_u1121u110c_jamo_seq,
	0x110c,
	0x1126,
	0,
	0,
	"u1121u110c",
};
static const uint16_t node_u1121u1110_jamo_seq[] = {
	0x1121,
	0x1110,
};
static const struct Node node_u1121u1110 = {
	187,
	2,
	node_u1121u1110_jamo_seq,
	0x1110,
	0xa972,
	0,
	0,
	"u1121u1110",
};
static const struct Node *node_u1121_children[] = {
	&node_u1121u1100,
	&node_u1121u1103,
	&node_u1121u1107,
	&node_u1121u1109,
	&node_u1121u110c,
	&node_u1121u1110,
};
static const uint16_t node_u1121_jamo_seq[] = {
	0x1121,
};
static const struct Node node_u1121 = {
	17,
	1,
	node_u1121_jamo_seq,
	0x1121,
	0,
	6,
	node_u1121_children,
	"u1121",
};
static const uint16_t node_u1132u1100_jamo_seq[] = {
	0x1132,
	0x1100,
};
static const struct Node node_u1132u1100 = {
	188,
	2,
	node_u1132u1100_jamo_seq,
	0x1100,
	0x1133,
	0,
	0,
	"u1132u1100",
};
static const struct Node *node_u1132_children[] = {
	&node_u1132u1100,
};
static const uint16_t node_u1132_jamo_seq[] = {
	0x1132,
};
static const struct Node node_u1132 = {
	18,
	1,
	node_u1132_jamo_seq,
	0x1132,
	0,
	1,
	node_u1132_children,
	"u1132",
};
static const uint16_t node_u113cu113c_jamo_seq[] = {
	0x113c,
	0x113c,
};
static const struct Node node_u113cu113c = {
	189,
	2,
	node_u113cu113c_jamo_seq,
	0x113c,
	0x113d,
	0,
	0,
	"u113cu113c",
};
static const struct Node *node_u113c_children[] = {
	&node_u113cu113c,
};
static const uint16_t node_u113c_jamo_seq[] = {
	0x113c,
};
static const struct Node node_u113c = {
	19,
	1,
	node_u113c_jamo_seq,
	0x113c,
	0,
	1,
	node_u113c_children,
	"u113c",
};
static const uint16_t node_u113eu113e_jamo_seq[] = {
	0x113e,
	0x113e,
};
static const struct Node node_u113eu113e = {
	190,
	2,
	node_u113eu113e_jamo_seq,
	0x113e,
	0x113f,
	0,
	0,
	"u113eu113e",
};
static const struct Node *node_u113e_children[] = {
	&node_u113eu113e,
};
static const uint16_t node_u113e_jamo_seq[] = {
	0x113e,
};
static const struct Node node_u113e = {
	20,
	1,
	node_u113e_jamo_seq,
	0x113e,
	0,
	1,
	node_u113e_children,
	"u113e",
};
static const uint16_t node_u114eu114e_jamo_seq[] = {
	0x114e,
	0x114e,
};
static const struct Node node_u114eu114e = {
	191,
	2,
	node_u114eu114e_jamo_seq,
	0x114e,
	0x114f,
	0,
	0,
	"u114eu114e",
};
static const struct Node *node_u114e_children[] = {
	&node_u114eu114e,
};
static const uint16_t node_u114e_jamo_seq[] = {
	0x114e,
};
static const struct Node node_u114e = {
	21,
	1,
	node_u114e_jamo_seq,
	0x114e,
	0,
	1,
	node_u114e_children,
	"u114e",
};
static const uint16_t node_u1150u1150_jamo_seq[] = {
	0x1150,
	0x1150,
};
static const struct Node node_u1150u1150 = {
	192,
	2,
	node_u1150u1150_jamo_seq,
	0x1150,
	0x1151,
	0,
	0,
	"u1150u1150",
};
static const struct Node *node_u1150_children[] = {
	&node_u1150u1150,
};
static const uint16_t node_u1150_jamo_seq[] = {
	0x1150,
};
static const struct Node node_u1150 = {
	22,
	1,
	node_u1150_jamo_seq,
	0x1150,
	0,
	1,
	node_u1150_children,
	"u1150",
};
static const uint16_t node_u1159u1159_jamo_seq[] = {
	0x1159,
	0x1159,
};
static const struct Node node_u1159u1159 = {
	193,
	2,
	node_u1159u1159_jamo_seq,
	0x1159,
	0xa97c,
	0,
	0,
	"u1159u1159",
};
static const struct Node *node_u1159_children[] = {
	&node_u1159u1159,
};
static const uint16_t node_u1159_jamo_seq[] = {
	0x1159,
};
static const struct Node node_u1159 = {
	23,
	1,
	node_u1159_jamo_seq,
	0x1159,
	0,
	1,
	node_u1159_children,
	"u1159",
};
static const uint16_t node_u1161u1169_jamo_seq[] = {
	0x1161,
	0x1169,
};
static const struct Node node_u1161u1169 = {
	194,
	2,
	node_u1161u1169_jamo_seq,
	0x1169,
	0x1176,
	0,
	0,
	"u1161u1169",
};
static const uint16_t node_u1161u116e_jamo_seq[] = {
	0x1161,
	0x116e,
};
static const struct Node node_u1161u116e = {
	195,
	2,
	node_u1161u116e_jamo_seq,
	0x116e,
	0x1177,
	0,
	0,
	"u1161u116e",
};
static const uint16_t node_u1161u1173_jamo_seq[] = {
	0x1161,
	0x1173,
};
static const struct Node node_u1161u1173 = {
	196,
	2,
	node_u1161u1173_jamo_seq,
	0x1173,
	0x11a3,
	0,
	0,
	"u1161u1173",
};
static const uint16_t node_u1161u1175_jamo_seq[] = {
	0x1161,
	0x1175,
};
static const struct Node node_u1161u1175 = {
	197,
	2,
	node_u1161u1175_jamo_seq,
	0x1175,
	0x1162,
	0,
	0,
	"u1161u1175",
};
static const struct Node *node_u1161_children[] = {
	&node_u1161u1169,
	&node_u1161u116e,
	&node_u1161u1173,
	&node_u1161u1175,
};
static const uint16_t node_u1161_jamo_seq[] = {
	0x1161,
};
static const struct Node node_u1161 = {
	24,
	1,
	node_u1161_jamo_seq,
	0x1161,
	0,
	4,
	node_u1161_children,
	"u1161",
};
static const uint16_t node_u1163u1169_jamo_seq[] = {
	0x1163,
	0x1169,
};
static const struct Node node_u1163u1169 = {
	198,
	2,
	node_u1163u1169_jamo_seq,
	0x1169,
	0x1178,
	0,
	0,
	"u1163u1169",
};
static const uint16_t node_u1163u116d_jamo_seq[] = {
	0x1163,
	0x116d,
};
static const struct Node node_u1163u116d = {
	199,
	2,
	node_u1163u116d_jamo_seq,
	0x116d,
	0x1179,
	0,
	0,
	"u1163u116d",
};
static const uint16_t node_u1163u116e_jamo_seq[] = {
	0x1163,
	0x116e,
};
static const struct Node node_u1163u116e = {
	200,
	2,
	node_u1163u116e_jamo_seq,
	0x116e,
	0x11a4,
	0,
	0,
	"u1163u116e",
};
static const uint16_t node_u1163u1175_jamo_seq[] = {
	0x1163,
	0x1175,
};
static const struct Node node_u1163u1175 = {
	201,
	2,
	node_u1163u1175_jamo_seq,
	0x1175,
	0x1164,
	0,
	0,
	"u1163u1175",
};
static const struct Node *node_u1163_children[] = {
	&node_u1163u1169,
	&node_u1163u116d,
	&node_u1163u116e,
	&node_u1163u1175,
};
static const uint16_t node_u1163_jamo_seq[] = {
	0x1163,
};
static const struct Node node_u1163 = {
	25,
	1,
	node_u1163_jamo_seq,
	0x1163,
	0,
	4,
	node_u1163_children,
	"u1163",
};
static const uint16_t node_u1165u1169_jamo_seq[] = {
	0x1165,
	0x1169,
};
static const struct Node node_u1165u1169 = {
	202,
	2,
	node_u1165u1169_jamo_seq,
	0x1169,
	0x117a,
	0,
	0,
	"u1165u1169",
};
static const uint16_t node_u1165u116e_jamo_seq[] = {
	0x1165,
	0x116e,
};
static const struct Node node_u1165u116e = {
	203,
	2,
	node_u1165u116e_jamo_seq,
	0x116e,
	0x117b,
	0,
	0,
	"u1165u116e",
};
static const uint16_t node_u1165u1173_jamo_seq[] = {
	0x1165,
	0x1173,
};
static const struct Node node_u1165u1173 = {
	204,
	2,
	node_u1165u1173_jamo_seq,
	0x1173,
	0x117c,
	0,
	0,
	"u1165u1173",
};
static const uint16_t node_u1165u1175_jamo_seq[] = {
	0x1165,
	0x1175,
};
static const struct Node node_u1165u1175 = {
	205,
	2,
	node_u1165u1175_jamo_seq,
	0x1175,
	0x1166,
	0,
	0,
	"u1165u1175",
};
static const struct Node *node_u1165_children[] = {
	&node_u1165u1169,
	&node_u1165u116e,
	&node_u1165u1173,
	&node_u1165u1175,
};
static const uint16_t node_u1165_jamo_seq[] = {
	0x1165,
};
static const struct Node node_u1165 = {
	26,
	1,
	node_u1165_jamo_seq,
	0x1165,
	0,
	4,
	node_u1165_children,
	"u1165",
};
static const uint16_t node_u1167u1163_jamo_seq[] = {
	0x1167,
	0x1163,
};
static const struct Node node_u1167u1163 = {
	206,
	2,
	node_u1167u1163_jamo_seq,
	0x1163,
	0x11a5,
	0,
	0,
	"u1167u1163",
};
static const uint16_t node_u1167u1169_jamo_seq[] = {
	0x1167,
	0x1169,
};
static const struct Node node_u1167u1169 = {
	207,
	2,
	node_u1167u1169_jamo_seq,
	0x1169,
	0x117d,
	0,
	0,
	"u1167u1169",
};
static const uint16_t node_u1167u116e_jamo_seq[] = {
	0x1167,
	0x116e,
};
static const struct Node node_u1167u116e = {
	208,
	2,
	node_u1167u116e_jamo_seq,
	0x116e,
	0x117e,
	0,
	0,
	"u1167u116e",
};
static const uint16_t node_u1167u1175_jamo_seq[] = {
	0x1167,
	0x1175,
};
static const struct Node node_u1167u1175 = {
	209,
	2,
	node_u1167u1175_jamo_seq,
	0x1175,
	0x1168,
	0,
	0,
	"u1167u1175",
};
static const struct Node *node_u1167_children[] = {
	&node_u1167u1163,
	&node_u1167u1169,
	&node_u1167u116e,
	&node_u1167u1175,
};
static const uint16_t node_u1167_jamo_seq[] = {
	0x1167,
};
static const struct Node node_u1167 = {
	27,
	1,
	node_u1167_jamo_seq,
	0x1167,
	0,
	4,
	node_u1167_children,
	"u1167",
};
static const uint16_t node_u1169u1161u1175_jamo_seq[] = {
	0x1169,
	0x1161,
	0x1175,
};
static const struct Node node_u1169u1161u1175 = {
	459,
	3,
	node_u1169u1161u1175_jamo_seq,
	0x1175,
	0x116b,
	0,
	0,
	"u1169u1161u1175",
};
static const struct Node *node_u1169u1161_children[] = {
	&node_u1169u1161u1175,
};
static const uint16_t node_u1169u1161_jamo_seq[] = {
	0x1169,
	0x1161,
};
static const struct Node node_u1169u1161 = {
	210,
	2,
	node_u1169u1161_jamo_seq,
	0x1161,
	0x116a,
	1,
	node_u1169u1161_children,
	"u1169u1161",
};
static const uint16_t node_u1169u1162_jamo_seq[] = {
	0x1169,
	0x1162,
};
static const struct Node node_u1169u1162 = {
	211,
	2,
	node_u1169u1162_jamo_seq,
	0x1162,
	0x116b,
	0,
	0,
	"u1169u1162",
};
static const uint16_t node_u1169u1163u1175_jamo_seq[] = {
	0x1169,
	0x1163,
	0x1175,
};
static const struct Node node_u1169u1163u1175 = {
	460,
	3,
	node_u1169u1163u1175_jamo_seq,
	0x1175,
	0x11a7,
	0,
	0,
	"u1169u1163u1175",
};
static const struct Node *node_u1169u1163_children[] = {
	&node_u1169u1163u1175,
};
static const uint16_t node_u1169u1163_jamo_seq[] = {
	0x1169,
	0x1163,
};
static const struct Node node_u1169u1163 = {
	212,
	2,
	node_u1169u1163_jamo_seq,
	0x1163,
	0x11a6,
	1,
	node_u1169u1163_children,
	"u1169u1163",
};
static const uint16_t node_u1169u1164_jamo_seq[] = {
	0x1169,
	0x1164,
};
static const struct Node node_u1169u1164 = {
	213,
	2,
	node_u1169u1164_jamo_seq,
	0x1164,
	0x11a7,
	0,
	0,
	"u1169u1164",
};
static const uint16_t node_u1169u1165u1175_jamo_seq[] = {
	0x1169,
	0x1165,
	0x1175,
};
static const struct Node node_u1169u1165u1175 = {
	461,
	3,
	node_u1169u1165u1175_jamo_seq,
	0x1175,
	0x1180,
	0,
	0,
	"u1169u1165u1175",
};
static const struct Node *node_u1169u1165_children[] = {
	&node_u1169u1165u1175,
};
static const uint16_t node_u1169u1165_jamo_seq[] = {
	0x1169,
	0x1165,
};
static const struct Node node_u1169u1165 = {
	214,
	2,
	node_u1169u1165_jamo_seq,
	0x1165,
	0x117f,
	1,
	node_u1169u1165_children,
	"u1169u1165",
};
static const uint16_t node_u1169u1166_jamo_seq[] = {
	0x1169,
	0x1166,
};
static const struct Node node_u1169u1166 = {
	215,
	2,
	node_u1169u1166_jamo_seq,
	0x1166,
	0x1180,
	0,
	0,
	"u1169u1166",
};
static const uint16_t node_u1169u1167u1175_jamo_seq[] = {
	0x1169,
	0x1167,
	0x1175,
};
static const struct Node node_u1169u1167u1175 = {
	462,
	3,
	node_u1169u1167u1175_jamo_seq,
	0x1175,
	0x1181,
	0,
	0,
	"u1169u1167u1175",
};
static const struct Node *node_u1169u1167_children[] = {
	&node_u1169u1167u1175,
};
static const uint16_t node_u1169u1167_jamo_seq[] = {
	0x1169,
	0x1167,
};
static const struct Node node_u1169u1167 = {
	216,
	2,
	node_u1169u1167_jamo_seq,
	0x1167,
	0xd7b0,
	1,
	node_u1169u1167_children,
	"u1169u1167",
};
static const uint16_t node_u1169u1168_jamo_seq[] = {
	0x1169,
	0x1168,
};
static const struct Node node_u1169u1168 = {
	217,
	2,
	node_u1169u1168_jamo_seq,
	0x1168,
	0x1181,
	0,
	0,
	"u1169u1168",
};
static const uint16_t node_u1169u1169u1175_jamo_seq[] = {
	0x1169,
	0x1169,
	0x1175,
};
static const struct Node node_u1169u1169u1175 = {
	463,
	3,
	node_u1169u1169u1175_jamo_seq,
	0x1175,
	0xd7b1,
	0,
	0,
	"u1169u1169u1175",
};
static const struct Node *node_u1169u1169_children[] = {
	&node_u1169u1169u1175,
};
static const uint16_t node_u1169u1169_jamo_seq[] = {
	0x1169,
	0x1169,
};
static const struct Node node_u1169u1169 = {
	218,
	2,
	node_u1169u1169_jamo_seq,
	0x1169,
	0x1182,
	1,
	node_u1169u1169_children,
	"u1169u1169",
};
static const uint16_t node_u1169u116c_jamo_seq[] = {
	0x1169,
	0x116c,
};
static const struct Node node_u1169u116c = {
	219,
	2,
	node_u1169u116c_jamo_seq,
	0x116c,
	0xd7b1,
	0,
	0,
	"u1169u116c",
};
static const uint16_t node_u1169u116e_jamo_seq[] = {
	0x1169,
	0x116e,
};
static const struct Node node_u1169u116e = {
	220,
	2,
	node_u1169u116e_jamo_seq,
	0x116e,
	0x1183,
	0,
	0,
	"u1169u116e",
};
static const uint16_t node_u1169u1175_jamo_seq[] = {
	0x1169,
	0x1175,
};
static const struct Node node_u1169u1175 = {
	221,
	2,
	node_u1169u1175_jamo_seq,
	0x1175,
	0x116c,
	0,
	0,
	"u1169u1175",
};
static const struct Node *node_u1169_children[] = {
	&node_u1169u1161,
	&node_u1169u1162,
	&node_u1169u1163,
	&node_u1169u1164,
	&node_u1169u1165,
	&node_u1169u1166,
	&node_u1169u1167,
	&node_u1169u1168,
	&node_u1169u1169,
	&node_u1169u116c,
	&node_u1169u116e,
	&node_u1169u1175,
};
static const uint16_t node_u1169_jamo_seq[] = {
	0x1169,
};
static const struct Node node_u1169 = {
	28,
	1,
	node_u1169_jamo_seq,
	0x1169,
	0,
	12,
	node_u1169_children,
	"u1169",
};
static const uint16_t node_u116au1175_jamo_seq[] = {
	0x116a,
	0x1175,
};
static const struct Node node_u116au1175 = {
	222,
	2,
	node_u116au1175_jamo_seq,
	0x1175,
	0x116b,
	0,
	0,
	"u116au1175",
};
static const struct Node *node_u116a_children[] = {
	&node_u116au1175,
};
static const uint16_t node_u116a_jamo_seq[] = {
	0x116a,
};
static const struct Node node_u116a = {
	29,
	1,
	node_u116a_jamo_seq,
	0x116a,
	0,
	1,
	node_u116a_children,
	"u116a",
};
static const uint16_t node_u116du1161u1175_jamo_seq[] = {
	0x116d,
	0x1161,
	0x1175,
};
static const struct Node node_u116du1161u1175 = {
	464,
	3,
	node_u116du1161u1175_jamo_seq,
	0x1175,
	0xd7b3,
	0,
	0,
	"u116du1161u1175",
};
static const struct Node *node_u116du1161_children[] = {
	&node_u116du1161u1175,
};
static const uint16_t node_u116du1161_jamo_seq[] = {
	0x116d,
	0x1161,
};
static const struct Node node_u116du1161 = {
	223,
	2,
	node_u116du1161_jamo_seq,
	0x1161,
	0xd7b2,
	1,
	node_u116du1161_children,
	"u116du1161",
};
static const uint16_t node_u116du1162_jamo_seq[] = {
	0x116d,
	0x1162,
};
static const struct Node node_u116du1162 = {
	224,
	2,
	node_u116du1162_jamo_seq,
	0x1162,
	0xd7b3,
	0,
	0,
	"u116du1162",
};
static const uint16_t node_u116du1163u1175_jamo_seq[] = {
	0x116d,
	0x1163,
	0x1175,
};
static const struct Node node_u116du1163u1175 = {
	465,
	3,
	node_u116du1163u1175_jamo_seq,
	0x1175,
	0x1185,
	0,
	0,
	"u116du1163u1175",
};
static const struct Node *node_u116du1163_children[] = {
	&node_u116du1163u1175,
};
static const uint16_t node_u116du1163_jamo_seq[] = {
	0x116d,
	0x1163,
};
static const struct Node node_u116du1163 = {
	225,
	2,
	node_u116du1163_jamo_seq,
	0x1163,
	0x1184,
	1,
	node_u116du1163_children,
	"u116du1163",
};
static const uint16_t node_u116du1164_jamo_seq[] = {
	0x116d,
	0x1164,
};
static const struct Node node_u116du1164 = {
	226,
	2,
	node_u116du1164_jamo_seq,
	0x1164,
	0x1185,
	0,
	0,
	"u116du1164",
};
static const uint16_t node_u116du1165_jamo_seq[] = {
	0x116d,
	0x1165,
};
static const struct Node node_u116du1165 = {
	227,
	2,
	node_u116du1165_jamo_seq,
	0x1165,
	0xd7b4,
	0,
	0,
	"u116du1165",
};
static const uint16_t node_u116du1167_jamo_seq[] = {
	0x116d,
	0x1167,
};
static const struct Node node_u116du1167 = {
	228,
	2,
	node_u116du1167_jamo_seq,
	0x1167,
	0x1186,
	0,
	0,
	"u116du1167",
};
static const uint16_t node_u116du1169_jamo_seq[] = {
	0x116d,
	0x1169,
};
static const struct Node node_u116du1169 = {
	229,
	2,
	node_u116du1169_jamo_seq,
	0x1169,
	0x1187,
	0,
	0,
	"u116du1169",
};
static const uint16_t node_u116du1175_jamo_seq[] = {
	0x116d,
	0x1175,
};
static const struct Node node_u116du1175 = {
	230,
	2,
	node_u116du1175_jamo_seq,
	0x1175,
	0x1188,
	0,
	0,
	"u116du1175",
};
static const struct Node *node_u116d_children[] = {
	&node_u116du1161,
	&node_u116du1162,
	&node_u116du1163,
	&node_u116du1164,
	&node_u116du1165,
	&node_u116du1167,
	&node_u116du1169,
	&node_u116du1175,
};
static const uint16_t node_u116d_jamo_seq[] = {
	0x116d,
};
static const struct Node node_u116d = {
	30,
	1,
	node_u116d_jamo_seq,
	0x116d,
	0,
	8,
	node_u116d_children,
	"u116d",
};
static const uint16_t node_u116eu1161u1175_jamo_seq[] = {
	0x116e,
	0x1161,
	0x1175,
};
static const struct Node node_u116eu1161u1175 = {
	466,
	3,
	node_u116eu1161u1175_jamo_seq,
	0x1175,
	0x118a,
	0,
	0,
	"u116eu1161u1175",
};
static const struct Node *node_u116eu1161_children[] = {
	&node_u116eu1161u1175,
};
static const uint16_t node_u116eu1161_jamo_seq[] = {
	0x116e,
	0x1161,
};
static const struct Node node_u116eu1161 = {
	231,
	2,
	node_u116eu1161_jamo_seq,
	0x1161,
	0x1189,
	1,
	node_u116eu1161_children,
	"u116eu1161",
};
static const uint16_t node_u116eu1162_jamo_seq[] = {
	0x116e,
	0x1162,
};
static const struct Node node_u116eu1162 = {
	232,
	2,
	node_u116eu1162_jamo_seq,
	0x1162,
	0x118a,
	0,
	0,
	"u116eu1162",
};
static const uint16_t node_u116eu1165u1173_jamo_seq[] = {
	0x116e,
	0x1165,
	0x1173,
};
static const struct Node node_u116eu1165u1173 = {
	467,
	3,
	node_u116eu1165u1173_jamo_seq,
	0x1173,
	0x118b,
	0,
	0,
	"u116eu1165u1173",
};
static const uint16_t node_u116eu1165u1175_jamo_seq[] = {
	0x116e,
	0x1165,
	0x1175,
};
static const struct Node node_u116eu1165u1175 = {
	468,
	3,
	node_u116eu1165u1175_jamo_seq,
	0x1175,
	0x1170,
	0,
	0,
	"u116eu1165u1175",
};
static const struct Node *node_u116eu1165_children[] = {
	&node_u116eu1165u1173,
	&node_u116eu1165u1175,
};
static const uint16_t node_u116eu1165_jamo_seq[] = {
	0x116e,
	0x1165,
};
static const struct Node node_u116eu1165 = {
	233,
	2,
	node_u116eu1165_jamo_seq,
	0x1165,
	0x116f,
	2,
	node_u116eu1165_children,
	"u116eu1165",
};
static const uint16_t node_u116eu1166_jamo_seq[] = {
	0x116e,
	0x1166,
};
static const struct Node node_u116eu1166 = {
	234,
	2,
	node_u116eu1166_jamo_seq,
	0x1166,
	0x1170,
	0,
	0,
	"u116eu1166",
};
static const uint16_t node_u116eu1167u1175_jamo_seq[] = {
	0x116e,
	0x1167,
	0x1175,
};
static const struct Node node_u116eu1167u1175 = {
	469,
	3,
	node_u116eu1167u1175_jamo_seq,
	0x1175,
	0x118c,
	0,
	0,
	"u116eu1167u1175",
};
static const struct Node *node_u116eu1167_children[] = {
	&node_u116eu1167u1175,
};
static const uint16_t node_u116eu1167_jamo_seq[] = {
	0x116e,
	0x1167,
};
static const struct Node node_u116eu1167 = {
	235,
	2,
	node_u116eu1167_jamo_seq,
	0x1167,
	0xd7b5,
	1,
	node_u116eu1167_children,
	"u116eu1167",
};
static const uint16_t node_u116eu1168_jamo_seq[] = {
	0x116e,
	0x1168,
};
static const struct Node node_u116eu1168 = {
	236,
	2,
	node_u116eu1168_jamo_seq,
	0x1168,
	0x118c,
	0,
	0,
	"u116eu1168",
};
static const uint16_t node_u116eu116e_jamo_seq[] = {
	0x116e,
	0x116e,
};
static const struct Node node_u116eu116e = {
	237,
	2,
	node_u116eu116e_jamo_seq,
	0x116e,
	0x118d,
	0,
	0,
	"u116eu116e",
};
static const uint16_t node_u116eu1175u1175_jamo_seq[] = {
	0x116e,
	0x1175,
	0x1175,
};
static const struct Node node_u116eu1175u1175 = {
	470,
	3,
	node_u116eu1175u1175_jamo_seq,
	0x1175,
	0xd7b6,
	0,
	0,
	"u116eu1175u1175",
};
static const struct Node *node_u116eu1175_children[] = {
	&node_u116eu1175u1175,
};
static const uint16_t node_u116eu1175_jamo_seq[] = {
	0x116e,
	0x1175,
};
static const struct Node node_u116eu1175 = {
	238,
	2,
	node_u116eu1175_jamo_seq,
	0x1175,
	0x1171,
	1,
	node_u116eu1175_children,
	"u116eu1175",
};
static const uint16_t node_u116eu117c_jamo_seq[] = {
	0x116e,
	0x117c,
};
static const struct Node node_u116eu117c = {
	239,
	2,
	node_u116eu117c_jamo_seq,
	0x117c,
	0x118b,
	0,
	0,
	"u116eu117c",
};
static const uint16_t node_u116eud7c4_jamo_seq[] = {
	0x116e,
	0xd7c4,
};
static const struct Node node_u116eud7c4 = {
	240,
	2,
	node_u116eud7c4_jamo_seq,
	0xd7c4,
	0xd7b6,
	0,
	0,
	"u116eud7c4",
};
static const struct Node *node_u116e_children[] = {
	&node_u116eu1161,
	&node_u116eu1162,
	&node_u116eu1165,
	&node_u116eu1166,
	&node_u116eu1167,
	&node_u116eu1168,
	&node_u116eu116e,
	&node_u116eu1175,
	&node_u116eu117c,
	&node_u116eud7c4,
};
static const uint16_t node_u116e_jamo_seq[] = {
	0x116e,
};
static const struct Node node_u116e = {
	31,
	1,
	node_u116e_jamo_seq,
	0x116e,
	0,
	10,
	node_u116e_children,
	"u116e",
};
static const uint16_t node_u116fu1173_jamo_seq[] = {
	0x116f,
	0x1173,
};
static const struct Node node_u116fu1173 = {
	241,
	2,
	node_u116fu1173_jamo_seq,
	0x1173,
	0x118b,
	0,
	0,
	"u116fu1173",
};
static const uint16_t node_u116fu1175_jamo_seq[] = {
	0x116f,
	0x1175,
};
static const struct Node node_u116fu1175 = {
	242,
	2,
	node_u116fu1175_jamo_seq,
	0x1175,
	0x1170,
	0,
	0,
	"u116fu1175",
};
static const struct Node *node_u116f_children[] = {
	&node_u116fu1173,
	&node_u116fu1175,
};
static const uint16_t node_u116f_jamo_seq[] = {
	0x116f,
};
static const struct Node node_u116f = {
	32,
	1,
	node_u116f_jamo_seq,
	0x116f,
	0,
	2,
	node_u116f_children,
	"u116f",
};
static const uint16_t node_u1171u1175_jamo_seq[] = {
	0x1171,
	0x1175,
};
static const struct Node node_u1171u1175 = {
	243,
	2,
	node_u1171u1175_jamo_seq,
	0x1175,
	0xd7b6,
	0,
	0,
	"u1171u1175",
};
static const struct Node *node_u1171_children[] = {
	&node_u1171u1175,
};
static const uint16_t node_u1171_jamo_seq[] = {
	0x1171,
};
static const struct Node node_u1171 = {
	33,
	1,
	node_u1171_jamo_seq,
	0x1171,
	0,
	1,
	node_u1171_children,
	"u1171",
};
static const uint16_t node_u1172u1161u1175_jamo_seq[] = {
	0x1172,
	0x1161,
	0x1175,
};
static const struct Node node_u1172u1161u1175 = {
	471,
	3,
	node_u1172u1161u1175_jamo_seq,
	0x1175,
	0xd7b7,
	0,
	0,
	"u1172u1161u1175",
};
static const struct Node *node_u1172u1161_children[] = {
	&node_u1172u1161u1175,
};
static const uint16_t node_u1172u1161_jamo_seq[] = {
	0x1172,
	0x1161,
};
static const struct Node node_u1172u1161 = {
	244,
	2,
	node_u1172u1161_jamo_seq,
	0x1161,
	0x118e,
	1,
	node_u1172u1161_children,
	"u1172u1161",
};
static const uint16_t node_u1172u1162_jamo_seq[] = {
	0x1172,
	0x1162,
};
static const struct Node node_u1172u1162 = {
	245,
	2,
	node_u1172u1162_jamo_seq,
	0x1162,
	0xd7b7,
	0,
	0,
	"u1172u1162",
};
static const uint16_t node_u1172u1165u1175_jamo_seq[] = {
	0x1172,
	0x1165,
	0x1175,
};
static const struct Node node_u1172u1165u1175 = {
	472,
	3,
	node_u1172u1165u1175_jamo_seq,
	0x1175,
	0x1190,
	0,
	0,
	"u1172u1165u1175",
};
static const struct Node *node_u1172u1165_children[] = {
	&node_u1172u1165u1175,
};
static const uint16_t node_u1172u1165_jamo_seq[] = {
	0x1172,
	0x1165,
};
static const struct Node node_u1172u1165 = {
	246,
	2,
	node_u1172u1165_jamo_seq,
	0x1165,
	0x118f,
	1,
	node_u1172u1165_children,
	"u1172u1165",
};
static const uint16_t node_u1172u1166_jamo_seq[] = {
	0x1172,
	0x1166,
};
static const struct Node node_u1172u1166 = {
	247,
	2,
	node_u1172u1166_jamo_seq,
	0x1166,
	0x1190,
	0,
	0,
	"u1172u1166",
};
static const uint16_t node_u1172u1167u1175_jamo_seq[] = {
	0x1172,
	0x1167,
	0x1175,
};
static const struct Node node_u1172u1167u1175 = {
	473,
	3,
	node_u1172u1167u1175_jamo_seq,
	0x1175,
	0x1192,
	0,
	0,
	"u1172u1167u1175",
};
static const struct Node *node_u1172u1167_children[] = {
	&node_u1172u1167u1175,
};
static const uint16_t node_u1172u1167_jamo_seq[] = {
	0x1172,
	0x1167,
};
static const struct Node node_u1172u1167 = {
	248,
	2,
	node_u1172u1167_jamo_seq,
	0x1167,
	0x1191,
	1,
	node_u1172u1167_children,
	"u1172u1167",
};
static const uint16_t node_u1172u1168_jamo_seq[] = {
	0x1172,
	0x1168,
};
static const struct Node node_u1172u1168 = {
	249,
	2,
	node_u1172u1168_jamo_seq,
	0x1168,
	0x1192,
	0,
	0,
	"u1172u1168",
};
static const uint16_t node_u1172u1169_jamo_seq[] = {
	0x1172,
	0x1169,
};
static const struct Node node_u1172u1169 = {
	250,
	2,
	node_u1172u1169_jamo_seq,
	0x1169,
	0xd7b8,
	0,
	0,
	"u1172u1169",
};
static const uint16_t node_u1172u116e_jamo_seq[] = {
	0x1172,
	0x116e,
};
static const struct Node node_u1172u116e = {
	251,
	2,
	node_u1172u116e_jamo_seq,
	0x116e,
	0x1193,
	0,
	0,
	"u1172u116e",
};
static const uint16_t node_u1172u1175_jamo_seq[] = {
	0x1172,
	0x1175,
};
static const struct Node node_u1172u1175 = {
	252,
	2,
	node_u1172u1175_jamo_seq,
	0x1175,
	0x1194,
	0,
	0,
	"u1172u1175",
};
static const struct Node *node_u1172_children[] = {
	&node_u1172u1161,
	&node_u1172u1162,
	&node_u1172u1165,
	&node_u1172u1166,
	&node_u1172u1167,
	&node_u1172u1168,
	&node_u1172u1169,
	&node_u1172u116e,
	&node_u1172u1175,
};
static const uint16_t node_u1172_jamo_seq[] = {
	0x1172,
};
static const struct Node node_u1172 = {
	34,
	1,
	node_u1172_jamo_seq,
	0x1172,
	0,
	9,
	node_u1172_children,
	"u1172",
};
static const uint16_t node_u1173u1161_jamo_seq[] = {
	0x1173,
	0x1161,
};
static const struct Node node_u1173u1161 = {
	253,
	2,
	node_u1173u1161_jamo_seq,
	0x1161,
	0xd7b9,
	0,
	0,
	"u1173u1161",
};
static const uint16_t node_u1173u1165u1175_jamo_seq[] = {
	0x1173,
	0x1165,
	0x1175,
};
static const struct Node node_u1173u1165u1175 = {
	474,
	3,
	node_u1173u1165u1175_jamo_seq,
	0x1175,
	0xd7bb,
	0,
	0,
	"u1173u1165u1175",
};
static const struct Node *node_u1173u1165_children[] = {
	&node_u1173u1165u1175,
};
static const uint16_t node_u1173u1165_jamo_seq[] = {
	0x1173,
	0x1165,
};
static const struct Node node_u1173u1165 = {
	254,
	2,
	node_u1173u1165_jamo_seq,
	0x1165,
	0xd7ba,
	1,
	node_u1173u1165_children,
	"u1173u1165",
};
static const uint16_t node_u1173u1166_jamo_seq[] = {
	0x1173,
	0x1166,
};
static const struct Node node_u1173u1166 = {
	255,
	2,
	node_u1173u1166_jamo_seq,
	0x1166,
	0xd7bb,
	0,
	0,
	"u1173u1166",
};
static const uint16_t node_u1173u1169_jamo_seq[] = {
	0x1173,
	0x1169,
};
static const struct Node node_u1173u1169 = {
	256,
	2,
	node_u1173u1169_jamo_seq,
	0x1169,
	0xd7bc,
	0,
	0,
	"u1173u1169",
};
static const uint16_t node_u1173u116e_jamo_seq[] = {
	0x1173,
	0x116e,
};
static const struct Node node_u1173u116e = {
	257,
	2,
	node_u1173u116e_jamo_seq,
	0x116e,
	0x1195,
	0,
	0,
	"u1173u116e",
};
static const uint16_t node_u1173u1173_jamo_seq[] = {
	0x1173,
	0x1173,
};
static const struct Node node_u1173u1173 = {
	258,
	2,
	node_u1173u1173_jamo_seq,
	0x1173,
	0x1196,
	0,
	0,
	"u1173u1173",
};
static const uint16_t node_u1173u1175u116e_jamo_seq[] = {
	0x1173,
	0x1175,
	0x116e,
};
static const struct Node node_u1173u1175u116e = {
	475,
	3,
	node_u1173u1175u116e_jamo_seq,
	0x116e,
	0x1197,
	0,
	0,
	"u1173u1175u116e",
};
static const struct Node *node_u1173u1175_children[] = {
	&node_u1173u1175u116e,
};
static const uint16_t node_u1173u1175_jamo_seq[] = {
	0x1173,
	0x1175,
};
static const struct Node node_u1173u1175 = {
	259,
	2,
	node_u1173u1175_jamo_seq,
	0x1175,
	0x1174,
	1,
	node_u1173u1175_children,
	"u1173u1175",
};
static const uint16_t node_u1173u119b_jamo_seq[] = {
	0x1173,
	0x119b,
};
static const struct Node node_u1173u119b = {
	260,
	2,
	node_u1173u119b_jamo_seq,
	0x119b,
	0x1197,
	0,
	0,
	"u1173u119b",
};
static const struct Node *node_u1173_children[] = {
	&node_u1173u1161,
	&node_u1173u1165,
	&node_u1173u1166,
	&node_u1173u1169,
	&node_u1173u116e,
	&node_u1173u1173,
	&node_u1173u1175,
	&node_u1173u119b,
};
static const uint16_t node_u1173_jamo_seq[] = {
	0x1173,
};
static const struct Node node_u1173 = {
	35,
	1,
	node_u1173_jamo_seq,
	0x1173,
	0,
	8,
	node_u1173_children,
	"u1173",
};
static const uint16_t node_u1174u116e_jamo_seq[] = {
	0x1174,
	0x116e,
};
static const struct Node node_u1174u116e = {
	261,
	2,
	node_u1174u116e_jamo_seq,
	0x116e,
	0x1197,
	0,
	0,
	"u1174u116e",
};
static const struct Node *node_u1174_children[] = {
	&node_u1174u116e,
};
static const uint16_t node_u1174_jamo_seq[] = {
	0x1174,
};
static const struct Node node_u1174 = {
	36,
	1,
	node_u1174_jamo_seq,
	0x1174,
	0,
	1,
	node_u1174_children,
	"u1174",
};
static const uint16_t node_u1175u1161_jamo_seq[] = {
	0x1175,
	0x1161,
};
static const struct Node node_u1175u1161 = {
	262,
	2,
	node_u1175u1161_jamo_seq,
	0x1161,
	0x1198,
	0,
	0,
	"u1175u1161",
};
static const uint16_t node_u1175u1163u1169_jamo_seq[] = {
	0x1175,
	0x1163,
	0x1169,
};
static const struct Node node_u1175u1163u1169 = {
	476,
	3,
	node_u1175u1163u1169_jamo_seq,
	0x1169,
	0xd7bd,
	0,
	0,
	"u1175u1163u1169",
};
static const uint16_t node_u1175u1163u1175_jamo_seq[] = {
	0x1175,
	0x1163,
	0x1175,
};
static const struct Node node_u1175u1163u1175 = {
	477,
	3,
	node_u1175u1163u1175_jamo_seq,
	0x1175,
	0xd7be,
	0,
	0,
	"u1175u1163u1175",
};
static const struct Node *node_u1175u1163_children[] = {
	&node_u1175u1163u1169,
	&node_u1175u1163u1175,
};
static const uint16_t node_u1175u1163_jamo_seq[] = {
	0x1175,
	0x1163,
};
static const struct Node node_u1175u1163 = {
	263,
	2,
	node_u1175u1163_jamo_seq,
	0x1163,
	0x1199,
	2,
	node_u1175u1163_children,
	"u1175u1163",
};
static const uint16_t node_u1175u1164_jamo_seq[] = {
	0x1175,
	0x1164,
};
static const struct Node node_u1175u1164 = {
	264,
	2,
	node_u1175u1164_jamo_seq,
	0x1164,
	0xd7be,
	0,
	0,
	"u1175u1164",
};
static const uint16_t node_u1175u1167u1175_jamo_seq[] = {
	0x1175,
	0x1167,
	0x1175,
};
static const struct Node node_u1175u1167u1175 = {
	478,
	3,
	node_u1175u1167u1175_jamo_seq,
	0x1175,
	0xd7c0,
	0,
	0,
	"u1175u1167u1175",
};
static const struct Node *node_u1175u1167_children[] = {
	&node_u1175u1167u1175,
};
static const uint16_t node_u1175u1167_jamo_seq[] = {
	0x1175,
	0x1167,
};
static const struct Node node_u1175u1167 = {
	265,
	2,
	node_u1175u1167_jamo_seq,
	0x1167,
	0xd7bf,
	1,
	node_u1175u1167_children,
	"u1175u1167",
};
static const uint16_t node_u1175u1168_jamo_seq[] = {
	0x1175,
	0x1168,
};
static const struct Node node_u1175u1168 = {
	266,
	2,
	node_u1175u1168_jamo_seq,
	0x1168,
	0xd7c0,
	0,
	0,
	"u1175u1168",
};
static const uint16_t node_u1175u1169u1175_jamo_seq[] = {
	0x1175,
	0x1169,
	0x1175,
};
static const struct Node node_u1175u1169u1175 = {
	479,
	3,
	node_u1175u1169u1175_jamo_seq,
	0x1175,
	0xd7c1,
	0,
	0,
	"u1175u1169u1175",
};
static const struct Node *node_u1175u1169_children[] = {
	&node_u1175u1169u1175,
};
static const uint16_t node_u1175u1169_jamo_seq[] = {
	0x1175,
	0x1169,
};
static const struct Node node_u1175u1169 = {
	267,
	2,
	node_u1175u1169_jamo_seq,
	0x1169,
	0x119a,
	1,
	node_u1175u1169_children,
	"u1175u1169",
};
static const uint16_t node_u1175u116c_jamo_seq[] = {
	0x1175,
	0x116c,
};
static const struct Node node_u1175u116c = {
	268,
	2,
	node_u1175u116c_jamo_seq,
	0x116c,
	0xd7c1,
	0,
	0,
	"u1175u116c",
};
static const uint16_t node_u1175u116d_jamo_seq[] = {
	0x1175,
	0x116d,
};
static const struct Node node_u1175u116d = {
	269,
	2,
	node_u1175u116d_jamo_seq,
	0x116d,
	0xd7c2,
	0,
	0,
	"u1175u116d",
};
static const uint16_t node_u1175u116e_jamo_seq[] = {
	0x1175,
	0x116e,
};
static const struct Node node_u1175u116e = {
	270,
	2,
	node_u1175u116e_jamo_seq,
	0x116e,
	0x119b,
	0,
	0,
	"u1175u116e",
};
static const uint16_t node_u1175u1172_jamo_seq[] = {
	0x1175,
	0x1172,
};
static const struct Node node_u1175u1172 = {
	271,
	2,
	node_u1175u1172_jamo_seq,
	0x1172,
	0xd7c3,
	0,
	0,
	"u1175u1172",
};
static const uint16_t node_u1175u1173_jamo_seq[] = {
	0x1175,
	0x1173,
};
static const struct Node node_u1175u1173 = {
	272,
	2,
	node_u1175u1173_jamo_seq,
	0x1173,
	0x119c,
	0,
	0,
	"u1175u1173",
};
static const uint16_t node_u1175u1175_jamo_seq[] = {
	0x1175,
	0x1175,
};
static const struct Node node_u1175u1175 = {
	273,
	2,
	node_u1175u1175_jamo_seq,
	0x1175,
	0xd7c4,
	0,
	0,
	"u1175u1175",
};
static const uint16_t node_u1175u1178_jamo_seq[] = {
	0x1175,
	0x1178,
};
static const struct Node node_u1175u1178 = {
	274,
	2,
	node_u1175u1178_jamo_seq,
	0x1178,
	0xd7bd,
	0,
	0,
	"u1175u1178",
};
static const uint16_t node_u1175u119e_jamo_seq[] = {
	0x1175,
	0x119e,
};
static const struct Node node_u1175u119e = {
	275,
	2,
	node_u1175u119e_jamo_seq,
	0x119e,
	0x119d,
	0,
	0,
	"u1175u119e",
};
static const struct Node *node_u1175_children[] = {
	&node_u1175u1161,
	&node_u1175u1163,
	&node_u1175u1164,
	&node_u1175u1167,
	&node_u1175u1168,
	&node_u1175u1169,
	&node_u1175u116c,
	&node_u1175u116d,
	&node_u1175u116e,
	&node_u1175u1172,
	&node_u1175u1173,
	&node_u1175u1175,
	&node_u1175u1178,
	&node_u1175u119e,
};
static const uint16_t node_u1175_jamo_seq[] = {
	0x1175,
};
static const struct Node node_u1175 = {
	37,
	1,
	node_u1175_jamo_seq,
	0x1175,
	0,
	14,
	node_u1175_children,
	"u1175",
};
static const uint16_t node_u117fu1175_jamo_seq[] = {
	0x117f,
	0x1175,
};
static const struct Node node_u117fu1175 = {
	276,
	2,
	node_u117fu1175_jamo_seq,
	0x1175,
	0x1180,
	0,
	0,
	"u117fu1175",
};
static const struct Node *node_u117f_children[] = {
	&node_u117fu1175,
};
static const uint16_t node_u117f_jamo_seq[] = {
	0x117f,
};
static const struct Node node_u117f = {
	38,
	1,
	node_u117f_jamo_seq,
	0x117f,
	0,
	1,
	node_u117f_children,
	"u117f",
};
static const uint16_t node_u1182u1175_jamo_seq[] = {
	0x1182,
	0x1175,
};
static const struct Node node_u1182u1175 = {
	277,
	2,
	node_u1182u1175_jamo_seq,
	0x1175,
	0xd7b1,
	0,
	0,
	"u1182u1175",
};
static const struct Node *node_u1182_children[] = {
	&node_u1182u1175,
};
static const uint16_t node_u1182_jamo_seq[] = {
	0x1182,
};
static const struct Node node_u1182 = {
	39,
	1,
	node_u1182_jamo_seq,
	0x1182,
	0,
	1,
	node_u1182_children,
	"u1182",
};
static const uint16_t node_u1184u1175_jamo_seq[] = {
	0x1184,
	0x1175,
};
static const struct Node node_u1184u1175 = {
	278,
	2,
	node_u1184u1175_jamo_seq,
	0x1175,
	0x1185,
	0,
	0,
	"u1184u1175",
};
static const struct Node *node_u1184_children[] = {
	&node_u1184u1175,
};
static const uint16_t node_u1184_jamo_seq[] = {
	0x1184,
};
static const struct Node node_u1184 = {
	40,
	1,
	node_u1184_jamo_seq,
	0x1184,
	0,
	1,
	node_u1184_children,
	"u1184",
};
static const uint16_t node_u1189u1175_jamo_seq[] = {
	0x1189,
	0x1175,
};
static const struct Node node_u1189u1175 = {
	279,
	2,
	node_u1189u1175_jamo_seq,
	0x1175,
	0x118a,
	0,
	0,
	"u1189u1175",
};
static const struct Node *node_u1189_children[] = {
	&node_u1189u1175,
};
static const uint16_t node_u1189_jamo_seq[] = {
	0x1189,
};
static const struct Node node_u1189 = {
	41,
	1,
	node_u1189_jamo_seq,
	0x1189,
	0,
	1,
	node_u1189_children,
	"u1189",
};
static const uint16_t node_u118fu1175_jamo_seq[] = {
	0x118f,
	0x1175,
};
static const struct Node node_u118fu1175 = {
	280,
	2,
	node_u118fu1175_jamo_seq,
	0x1175,
	0x1190,
	0,
	0,
	"u118fu1175",
};
static const struct Node *node_u118f_children[] = {
	&node_u118fu1175,
};
static const uint16_t node_u118f_jamo_seq[] = {
	0x118f,
};
static const struct Node node_u118f = {
	42,
	1,
	node_u118f_jamo_seq,
	0x118f,
	0,
	1,
	node_u118f_children,
	"u118f",
};
static const uint16_t node_u1191u1175_jamo_seq[] = {
	0x1191,
	0x1175,
};
static const struct Node node_u1191u1175 = {
	281,
	2,
	node_u1191u1175_jamo_seq,
	0x1175,
	0x1192,
	0,
	0,
	"u1191u1175",
};
static const struct Node *node_u1191_children[] = {
	&node_u1191u1175,
};
static const uint16_t node_u1191_jamo_seq[] = {
	0x1191,
};
static const struct Node node_u1191 = {
	43,
	1,
	node_u1191_jamo_seq,
	0x1191,
	0,
	1,
	node_u1191_children,
	"u1191",
};
static const uint16_t node_u1199u1169_jamo_seq[] = {
	0x1199,
	0x1169,
};
static const struct Node node_u1199u1169 = {
	282,
	2,
	node_u1199u1169_jamo_seq,
	0x1169,
	0xd7bd,
	0,
	0,
	"u1199u1169",
};
static const struct Node *node_u1199_children[] = {
	&node_u1199u1169,
};
static const uint16_t node_u1199_jamo_seq[] = {
	0x1199,
};
static const struct Node node_u1199 = {
	44,
	1,
	node_u1199_jamo_seq,
	0x1199,
	0,
	1,
	node_u1199_children,
	"u1199",
};
static const uint16_t node_u119au1175_jamo_seq[] = {
	0x119a,
	0x1175,
};
static const struct Node node_u119au1175 = {
	283,
	2,
	node_u119au1175_jamo_seq,
	0x1175,
	0xd7c1,
	0,
	0,
	"u119au1175",
};
static const struct Node *node_u119a_children[] = {
	&node_u119au1175,
};
static const uint16_t node_u119a_jamo_seq[] = {
	0x119a,
};
static const struct Node node_u119a = {
	45,
	1,
	node_u119a_jamo_seq,
	0x119a,
	0,
	1,
	node_u119a_children,
	"u119a",
};
static const uint16_t node_u119eu1161_jamo_seq[] = {
	0x119e,
	0x1161,
};
static const struct Node node_u119eu1161 = {
	284,
	2,
	node_u119eu1161_jamo_seq,
	0x1161,
	0xd7c5,
	0,
	0,
	"u119eu1161",
};
static const uint16_t node_u119eu1165u1175_jamo_seq[] = {
	0x119e,
	0x1165,
	0x1175,
};
static const struct Node node_u119eu1165u1175 = {
	480,
	3,
	node_u119eu1165u1175_jamo_seq,
	0x1175,
	0xd7c6,
	0,
	0,
	"u119eu1165u1175",
};
static const struct Node *node_u119eu1165_children[] = {
	&node_u119eu1165u1175,
};
static const uint16_t node_u119eu1165_jamo_seq[] = {
	0x119e,
	0x1165,
};
static const struct Node node_u119eu1165 = {
	285,
	2,
	node_u119eu1165_jamo_seq,
	0x1165,
	0x119f,
	1,
	node_u119eu1165_children,
	"u119eu1165",
};
static const uint16_t node_u119eu1166_jamo_seq[] = {
	0x119e,
	0x1166,
};
static const struct Node node_u119eu1166 = {
	286,
	2,
	node_u119eu1166_jamo_seq,
	0x1166,
	0xd7c6,
	0,
	0,
	"u119eu1166",
};
static const uint16_t node_u119eu116e_jamo_seq[] = {
	0x119e,
	0x116e,
};
static const struct Node node_u119eu116e = {
	287,
	2,
	node_u119eu116e_jamo_seq,
	0x116e,
	0x11a0,
	0,
	0,
	"u119eu116e",
};
static const uint16_t node_u119eu1175_jamo_seq[] = {
	0x119e,
	0x1175,
};
static const struct Node node_u119eu1175 = {
	288,
	2,
	node_u119eu1175_jamo_seq,
	0x1175,
	0x11a1,
	0,
	0,
	"u119eu1175",
};
static const uint16_t node_u119eu119e_jamo_seq[] = {
	0x119e,
	0x119e,
};
static const struct Node node_u119eu119e = {
	289,
	2,
	node_u119eu119e_jamo_seq,
	0x119e,
	0x11a2,
	0,
	0,
	"u119eu119e",
};
static const struct Node *node_u119e_children[] = {
	&node_u119eu1161,
	&node_u119eu1165,
	&node_u119eu1166,
	&node_u119eu116e,
	&node_u119eu1175,
	&node_u119eu119e,
};
static const uint16_t node_u119e_jamo_seq[] = {
	0x119e,
};
static const struct Node node_u119e = {
	46,
	1,
	node_u119e_jamo_seq,
	0x119e,
	0,
	6,
	node_u119e_children,
	"u119e",
};
static const uint16_t node_u11a8u11a8_jamo_seq[] = {
	0x11a8,
	0x11a8,
};
static const struct Node node_u11a8u11a8 = {
	290,
	2,
	node_u11a8u11a8_jamo_seq,
	0x11a8,
	0x11a9,
	0,
	0,
	"u11a8u11a8",
};
static const uint16_t node_u11a8u11ab_jamo_seq[] = {
	0x11a8,
	0x11ab,
};
static const struct Node node_u11a8u11ab = {
	291,
	2,
	node_u11a8u11ab_jamo_seq,
	0x11ab,
	0x11fa,
	0,
	0,
	"u11a8u11ab",
};
static const uint16_t node_u11a8u11af_jamo_seq[] = {
	0x11a8,
	0x11af,
};
static const struct Node node_u11a8u11af = {
	292,
	2,
	node_u11a8u11af_jamo_seq,
	0x11af,
	0x11c3,
	0,
	0,
	"u11a8u11af",
};
static const uint16_t node_u11a8u11b8_jamo_seq[] = {
	0x11a8,
	0x11b8,
};
static const struct Node node_u11a8u11b8 = {
	293,
	2,
	node_u11a8u11b8_jamo_seq,
	0x11b8,
	0x11fb,
	0,
	0,
	"u11a8u11b8",
};
static const uint16_t node_u11a8u11bau11a8_jamo_seq[] = {
	0x11a8,
	0x11ba,
	0x11a8,
};
static const struct Node node_u11a8u11bau11a8 = {
	481,
	3,
	node_u11a8u11bau11a8_jamo_seq,
	0x11a8,
	0x11c4,
	0,
	0,
	"u11a8u11bau11a8",
};
static const struct Node *node_u11a8u11ba_children[] = {
	&node_u11a8u11bau11a8,
};
static const uint16_t node_u11a8u11ba_jamo_seq[] = {
	0x11a8,
	0x11ba,
};
static const struct Node node_u11a8u11ba = {
	294,
	2,
	node_u11a8u11ba_jamo_seq,
	0x11ba,
	0x11aa,
	1,
	node_u11a8u11ba_children,
	"u11a8u11ba",
};
static const uint16_t node_u11a8u11be_jamo_seq[] = {
	0x11a8,
	0x11be,
};
static const struct Node node_u11a8u11be = {
	295,
	2,
	node_u11a8u11be_jamo_seq,
	0x11be,
	0x11fc,
	0,
	0,
	"u11a8u11be",
};
static const uint16_t node_u11a8u11bf_jamo_seq[] = {
	0x11a8,
	0x11bf,
};
static const struct Node node_u11a8u11bf = {
	296,
	2,
	node_u11a8u11bf_jamo_seq,
	0x11bf,
	0x11fd,
	0,
	0,
	"u11a8u11bf",
};
static const uint16_t node_u11a8u11c2_jamo_seq[] = {
	0x11a8,
	0x11c2,
};
static const struct Node node_u11a8u11c2 = {
	297,
	2,
	node_u11a8u11c2_jamo_seq,
	0x11c2,
	0x11fe,
	0,
	0,
	"u11a8u11c2",
};
static const uint16_t node_u11a8u11e7_jamo_seq[] = {
	0x11a8,
	0x11e7,
};
static const struct Node node_u11a8u11e7 = {
	298,
	2,
	node_u11a8u11e7_jamo_seq,
	0x11e7,
	0x11c4,
	0,
	0,
	"u11a8u11e7",
};
static const struct Node *node_u11a8_children[] = {
	&node_u11a8u11a8,
	&node_u11a8u11ab,
	&node_u11a8u11af,
	&node_u11a8u11b8,
	&node_u11a8u11ba,
	&node_u11a8u11be,
	&node_u11a8u11bf,
	&node_u11a8u11c2,
	&node_u11a8u11e7,
};
static const uint16_t node_u11a8_jamo_seq[] = {
	0x11a8,
};
static const struct Node node_u11a8 = {
	47,
	1,
	node_u11a8_jamo_seq,
	0x11a8,
	0,
	9,
	node_u11a8_children,
	"u11a8",
};
static const uint16_t node_u11aau11a8_jamo_seq[] = {
	0x11aa,
	0x11a8,
};
static const struct Node node_u11aau11a8 = {
	299,
	2,
	node_u11aau11a8_jamo_seq,
	0x11a8,
	0x11c4,
	0,
	0,
	"u11aau11a8",
};
static const struct Node *node_u11aa_children[] = {
	&node_u11aau11a8,
};
static const uint16_t node_u11aa_jamo_seq[] = {
	0x11aa,
};
static const struct Node node_u11aa = {
	48,
	1,
	node_u11aa_jamo_seq,
	0x11aa,
	0,
	1,
	node_u11aa_children,
	"u11aa",
};
static const uint16_t node_u11abu11a8_jamo_seq[] = {
	0x11ab,
	0x11a8,
};
static const struct Node node_u11abu11a8 = {
	300,
	2,
	node_u11abu11a8_jamo_seq,
	0x11a8,
	0x11c5,
	0,
	0,
	"u11abu11a8",
};
static const uint16_t node_u11abu11ab_jamo_seq[] = {
	0x11ab,
	0x11ab,
};
static const struct Node node_u11abu11ab = {
	301,
	2,
	node_u11abu11ab_jamo_seq,
	0x11ab,
	0x11ff,
	0,
	0,
	"u11abu11ab",
};
static const uint16_t node_u11abu11ae_jamo_seq[] = {
	0x11ab,
	0x11ae,
};
static const struct Node node_u11abu11ae = {
	302,
	2,
	node_u11abu11ae_jamo_seq,
	0x11ae,
	0x11c6,
	0,
	0,
	"u11abu11ae",
};
static const uint16_t node_u11abu11af_jamo_seq[] = {
	0x11ab,
	0x11af,
};
static const struct Node node_u11abu11af = {
	303,
	2,
	node_u11abu11af_jamo_seq,
	0x11af,
	0xd7cb,
	0,
	0,
	"u11abu11af",
};
static const uint16_t node_u11abu11ba_jamo_seq[] = {
	0x11ab,
	0x11ba,
};
static const struct Node node_u11abu11ba = {
	304,
	2,
	node_u11abu11ba_jamo_seq,
	0x11ba,
	0x11c7,
	0,
	0,
	"u11abu11ba",
};
static const uint16_t node_u11abu11bd_jamo_seq[] = {
	0x11ab,
	0x11bd,
};
static const struct Node node_u11abu11bd = {
	305,
	2,
	node_u11abu11bd_jamo_seq,
	0x11bd,
	0x11ac,
	0,
	0,
	"u11abu11bd",
};
static const uint16_t node_u11abu11be_jamo_seq[] = {
	0x11ab,
	0x11be,
};
static const struct Node node_u11abu11be = {
	306,
	2,
	node_u11abu11be_jamo_seq,
	0x11be,
	0xd7cc,
	0,
	0,
	"u11abu11be",
};
static const uint16_t node_u11abu11c0_jamo_seq[] = {
	0x11ab,
	0x11c0,
};
static const struct Node node_u11abu11c0 = {
	307,
	2,
	node_u11abu11c0_jamo_seq,
	0x11c0,
	0x11c9,
	0,
	0,
	"u11abu11c0",
};
static const uint16_t node_u11abu11c2_jamo_seq[] = {
	0x11ab,
	0x11c2,
};
static const struct Node node_u11abu11c2 = {
	308,
	2,
	node_u11abu11c2_jamo_seq,
	0x11c2,
	0x11ad,
	0,
	0,
	"u11abu11c2",
};
static const uint16_t node_u11abu11eb_jamo_seq[] = {
	0x11ab,
	0x11eb,
};
static const struct Node node_u11abu11eb = {
	309,
	2,
	node_u11abu11eb_jamo_seq,
	0x11eb,
	0x11c8,
	0,
	0,
	"u11abu11eb",
};
static const struct Node *node_u11ab_children[] = {
	&node_u11abu11a8,
	&node_u11abu11ab,
	&node_u11abu11ae,
	&node_u11abu11af,
	&node_u11abu11ba,
	&node_u11abu11bd,
	&node_u11abu11be,
	&node_u11abu11c0,
	&node_u11abu11c2,
	&node_u11abu11eb,
};
static const uint16_t node_u11ab_jamo_seq[] = {
	0x11ab,
};
static const struct Node node_u11ab = {
	49,
	1,
	node_u11ab_jamo_seq,
	0x11ab,
	0,
	10,
	node_u11ab_children,
	"u11ab",
};
static const uint16_t node_u11aeu11a8_jamo_seq[] = {
	0x11ae,
	0x11a8,
};
static const struct Node node_u11aeu11a8 = {
	310,
	2,
	node_u11aeu11a8_jamo_seq,
	0x11a8,
	0x11ca,
	0,
	0,
	"u11aeu11a8",
};
static const uint16_t node_u11aeu11aeu11b8_jamo_seq[] = {
	0x11ae,
	0x11ae,
	0x11b8,
};
static const struct Node node_u11aeu11aeu11b8 = {
	482,
	3,
	node_u11aeu11aeu11b8_jamo_seq,
	0x11b8,
	0xd7ce,
	0,
	0,
	"u11aeu11aeu11b8",
};
static const struct Node *node_u11aeu11ae_children[] = {
	&node_u11aeu11aeu11b8,
};
static const uint16_t node_u11aeu11ae_jamo_seq[] = {
	0x11ae,
	0x11ae,
};
static const struct Node node_u11aeu11ae = {
	311,
	2,
	node_u11aeu11ae_jamo_seq,
	0x11ae,
	0xd7cd,
	1,
	node_u11aeu11ae_children,
	"u11aeu11ae",
};
static const uint16_t node_u11aeu11af_jamo_seq[] = {
	0x11ae,
	0x11af,
};
static const struct Node node_u11aeu11af = {
	312,
	2,
	node_u11aeu11af_jamo_seq,
	0x11af,
	0x11cb,
	0,
	0,
	"u11aeu11af",
};
static const uint16_t node_u11aeu11b8_jamo_seq[] = {
	0x11ae,
	0x11b8,
};
static const struct Node node_u11aeu11b8 = {
	313,
	2,
	node_u11aeu11b8_jamo_seq,
	0x11b8,
	0xd7cf,
	0,
	0,
	"u11aeu11b8",
};
static const uint16_t node_u11aeu11bau11a8_jamo_seq[] = {
	0x11ae,
	0x11ba,
	0x11a8,
};
static const struct Node node_u11aeu11bau11a8 = {
	483,
	3,
	node_u11aeu11bau11a8_jamo_seq,
	0x11a8,
	0xd7d1,
	0,
	0,
	"u11aeu11bau11a8",
};
static const struct Node *node_u11aeu11ba_children[] = {
	&node_u11aeu11bau11a8,
};
static const uint16_t node_u11aeu11ba_jamo_seq[] = {
	0x11ae,
	0x11ba,
};
static const struct Node node_u11aeu11ba = {
	314,
	2,
	node_u11aeu11ba_jamo_seq,
	0x11ba,
	0xd7d0,
	1,
	node_u11aeu11ba_children,
	"u11aeu11ba",
};
static const uint16_t node_u11aeu11bd_jamo_seq[] = {
	0x11ae,
	0x11bd,
};
static const struct Node node_u11aeu11bd = {
	315,
	2,
	node_u11aeu11bd_jamo_seq,
	0x11bd,
	0xd7d2,
	0,
	0,
	"u11aeu11bd",
};
static const uint16_t node_u11aeu11be_jamo_seq[] = {
	0x11ae,
	0x11be,
};
static const struct Node node_u11aeu11be = {
	316,
	2,
	node_u11aeu11be_jamo_seq,
	0x11be,
	0xd7d3,
	0,
	0,
	"u11aeu11be",
};
static const uint16_t node_u11aeu11c0_jamo_seq[] = {
	0x11ae,
	0x11c0,
};
static const struct Node node_u11aeu11c0 = {
	317,
	2,
	node_u11aeu11c0_jamo_seq,
	0x11c0,
	0xd7d4,
	0,
	0,
	"u11aeu11c0",
};
static const uint16_t node_u11aeu11e7_jamo_seq[] = {
	0x11ae,
	0x11e7,
};
static const struct Node node_u11aeu11e7 = {
	318,
	2,
	node_u11aeu11e7_jamo_seq,
	0x11e7,
	0xd7d1,
	0,
	0,
	"u11aeu11e7",
};
static const uint16_t node_u11aeud7cf_jamo_seq[] = {
	0x11ae,
	0xd7cf,
};
static const struct Node node_u11aeud7cf = {
	319,
	2,
	node_u11aeud7cf_jamo_seq,
	0xd7cf,
	0xd7ce,
	0,
	0,
	"u11aeud7cf",
};
static const struct Node *node_u11ae_children[] = {
	&node_u11aeu11a8,
	&node_u11aeu11ae,
	&node_u11aeu11af,
	&node_u11aeu11b8,
	&node_u11aeu11ba,
	&node_u11aeu11bd,
	&node_u11aeu11be,
	&node_u11aeu11c0,
	&node_u11aeu11e7,
	&node_u11aeud7cf,
};
static const uint16_t node_u11ae_jamo_seq[] = {
	0x11ae,
};
static const struct Node node_u11ae = {
	50,
	1,
	node_u11ae_jamo_seq,
	0x11ae,
	0,
	10,
	node_u11ae_children,
	"u11ae",
};
static const uint16_t node_u11afu11a8u11a8_jamo_seq[] = {
	0x11af,
	0x11a8,
	0x11a8,
};
static const struct Node node_u11afu11a8u11a8 = {
	484,
	3,
	node_u11afu11a8u11a8_jamo_seq,
	0x11a8,
	0xd7d5,
	0,
	0,
	"u11afu11a8u11a8",
};
static const uint16_t node_u11afu11a8u11ba_jamo_seq[] = {
	0x11af,
	0x11a8,
	0x11ba,
};
static const struct Node node_u11afu11a8u11ba = {
	485,
	3,
	node_u11afu11a8u11ba_jamo_seq,
	0x11ba,
	0x11cc,
	0,
	0,
	"u11afu11a8u11ba",
};
static const uint16_t node_u11afu11a8u11c2_jamo_seq[] = {
	0x11af,
	0x11a8,
	0x11c2,
};
static const struct Node node_u11afu11a8u11c2 = {
	486,
	3,
	node_u11afu11a8u11c2_jamo_seq,
	0x11c2,
	0xd7d6,
	0,
	0,
	"u11afu11a8u11c2",
};
static const struct Node *node_u11afu11a8_children[] = {
	&node_u11afu11a8u11a8,
	&node_u11afu11a8u11ba,
	&node_u11afu11a8u11c2,
};
static const uint16_t node_u11afu11a8_jamo_seq[] = {
	0x11af,
	0x11a8,
};
static const struct Node node_u11afu11a8 = {
	320,
	2,
	node_u11afu11a8_jamo_seq,
	0x11a8,
	0x11b0,
	3,
	node_u11afu11a8_children,
	"u11afu11a8",
};
static const uint16_t node_u11afu11a9_jamo_seq[] = {
	0x11af,
	0x11a9,
};
static const struct Node node_u11afu11a9 = {
	321,
	2,
	node_u11afu11a9_jamo_seq,
	0x11a9,
	0xd7d5,
	0,
	0,
	"u11afu11a9",
};
static const uint16_t node_u11afu11aa_jamo_seq[] = {
	0x11af,
	0x11aa,
};
static const struct Node node_u11afu11aa = {
	322,
	2,
	node_u11afu11aa_jamo_seq,
	0x11aa,
	0x11cc,
	0,
	0,
	"u11afu11aa",
};
static const uint16_t node_u11afu11ab_jamo_seq[] = {
	0x11af,
	0x11ab,
};
static const struct Node node_u11afu11ab = {
	323,
	2,
	node_u11afu11ab_jamo_seq,
	0x11ab,
	0x11cd,
	0,
	0,
	"u11afu11ab",
};
static const uint16_t node_u11afu11aeu11c2_jamo_seq[] = {
	0x11af,
	0x11ae,
	0x11c2,
};
static const struct Node node_u11afu11aeu11c2 = {
	487,
	3,
	node_u11afu11aeu11c2_jamo_seq,
	0x11c2,
	0x11cf,
	0,
	0,
	"u11afu11aeu11c2",
};
static const struct Node *node_u11afu11ae_children[] = {
	&node_u11afu11aeu11c2,
};
static const uint16_t node_u11afu11ae_jamo_seq[] = {
	0x11af,
	0x11ae,
};
static const struct Node node_u11afu11ae = {
	324,
	2,
	node_u11afu11ae_jamo_seq,
	0x11ae,
	0x11ce,
	1,
	node_u11afu11ae_children,
	"u11afu11ae",
};
static const uint16_t node_u11afu11afu11bf_jamo_seq[] = {
	0x11af,
	0x11af,
	0x11bf,
};
static const struct Node node_u11afu11afu11bf = {
	488,
	3,
	node_u11afu11afu11bf_jamo_seq,
	0x11bf,
	0xd7d7,
	0,
	0,
	"u11afu11afu11bf",
};
static const struct Node *node_u11afu11af_children[] = {
	&node_u11afu11afu11bf,
};
static const uint16_t node_u11afu11af_jamo_seq[] = {
	0x11af,
	0x11af,
};
static const struct Node node_u11afu11af = {
	325,
	2,
	node_u11afu11af_jamo_seq,
	0x11af,
	0x11d0,
	1,
	node_u11afu11af_children,
	"u11afu11af",
};
static const uint16_t node_u11afu11b7u11a8_jamo_seq[] = {
	0x11af,
	0x11b7,
	0x11a8,
};
static const struct Node node_u11afu11b7u11a8 = {
	489,
	3,
	node_u11afu11b7u11a8_jamo_seq,
	0x11a8,
	0x11d1,
	0,
	0,
	"u11afu11b7u11a8",
};
static const uint16_t node_u11afu11b7u11ba_jamo_seq[] = {
	0x11af,
	0x11b7,
	0x11ba,
};
static const struct Node node_u11afu11b7u11ba = {
	490,
	3,
	node_u11afu11b7u11ba_jamo_seq,
	0x11ba,
	0x11d2,
	0,
	0,
	"u11afu11b7u11ba",
};
static const uint16_t node_u11afu11b7u11c2_jamo_seq[] = {
	0x11af,
	0x11b7,
	0x11c2,
};
static const struct Node node_u11afu11b7u11c2 = {
	491,
	3,
	node_u11afu11b7u11c2_jamo_seq,
	0x11c2,
	0xd7d8,
	0,
	0,
	"u11afu11b7u11c2",
};
static const struct Node *node_u11afu11b7_children[] = {
	&node_u11afu11b7u11a8,
	&node_u11afu11b7u11ba,
	&node_u11afu11b7u11c2,
};
static const uint16_t node_u11afu11b7_jamo_seq[] = {
	0x11af,
	0x11b7,
};
static const struct Node node_u11afu11b7 = {
	326,
	2,
	node_u11afu11b7_jamo_seq,
	0x11b7,
	0x11b1,
	3,
	node_u11afu11b7_children,
	"u11afu11b7",
};
static const uint16_t node_u11afu11b8u11ae_jamo_seq[] = {
	0x11af,
	0x11b8,
	0x11ae,
};
static const struct Node node_u11afu11b8u11ae = {
	492,
	3,
	node_u11afu11b8u11ae_jamo_seq,
	0x11ae,
	0xd7d9,
	0,
	0,
	"u11afu11b8u11ae",
};
static const uint16_t node_u11afu11b8u11ba_jamo_seq[] = {
	0x11af,
	0x11b8,
	0x11ba,
};
static const struct Node node_u11afu11b8u11ba = {
	493,
	3,
	node_u11afu11b8u11ba_jamo_seq,
	0x11ba,
	0x11d3,
	0,
	0,
	"u11afu11b8u11ba",
};
static const uint16_t node_u11afu11b8u11bc_jamo_seq[] = {
	0x11af,
	0x11b8,
	0x11bc,
};
static const struct Node node_u11afu11b8u11bc = {
	494,
	3,
	node_u11afu11b8u11bc_jamo_seq,
	0x11bc,
	0x11d5,
	0,
	0,
	"u11afu11b8u11bc",
};
static const uint16_t node_u11afu11b8u11c1_jamo_seq[] = {
	0x11af,
	0x11b8,
	0x11c1,
};
static const struct Node node_u11afu11b8u11c1 = {
	495,
	3,
	node_u11afu11b8u11c1_jamo_seq,
	0x11c1,
	0xd7da,
	0,
	0,
	"u11afu11b8u11c1",
};
static const uint16_t node_u11afu11b8u11c2_jamo_seq[] = {
	0x11af,
	0x11b8,
	0x11c2,
};
static const struct Node node_u11afu11b8u11c2 = {
	496,
	3,
	node_u11afu11b8u11c2_jamo_seq,
	0x11c2,
	0x11d4,
	0,
	0,
	"u11afu11b8u11c2",
};
static const struct Node *node_u11afu11b8_children[] = {
	&node_u11afu11b8u11ae,
	&node_u11afu11b8u11ba,
	&node_u11afu11b8u11bc,
	&node_u11afu11b8u11c1,
	&node_u11afu11b8u11c2,
};
static const uint16_t node_u11afu11b8_jamo_seq[] = {
	0x11af,
	0x11b8,
};
static const struct Node node_u11afu11b8 = {
	327,
	2,
	node_u11afu11b8_jamo_seq,
	0x11b8,
	0x11b2,
	5,
	node_u11afu11b8_children,
	"u11afu11b8",
};
static const uint16_t node_u11afu11b9_jamo_seq[] = {
	0x11af,
	0x11b9,
};
static const struct Node node_u11afu11b9 = {
	328,
	2,
	node_u11afu11b9_jamo_seq,
	0x11b9,
	0x11d3,
	0,
	0,
	"u11afu11b9",
};
static const uint16_t node_u11afu11bau11ba_jamo_seq[] = {
	0x11af,
	0x11ba,
	0x11ba,
};
static const struct Node node_u11afu11bau11ba = {
	497,
	3,
	node_u11afu11bau11ba_jamo_seq,
	0x11ba,
	0x11d6,
	0,
	0,
	"u11afu11bau11ba",
};
static const struct Node *node_u11afu11ba_children[] = {
	&node_u11afu11bau11ba,
};
static const uint16_t node_u11afu11ba_jamo_seq[] = {
	0x11af,
	0x11ba,
};
static const struct Node node_u11afu11ba = {
	329,
	2,
	node_u11afu11ba_jamo_seq,
	0x11ba,
	0x11b3,
	1,
	node_u11afu11ba_children,
	"u11afu11ba",
};
static const uint16_t node_u11afu11bb_jamo_seq[] = {
	0x11af,
	0x11bb,
};
static const struct Node node_u11afu11bb = {
	330,
	2,
	node_u11afu11bb_jamo_seq,
	0x11bb,
	0x11d6,
	0,
	0,
	"u11afu11bb",
};
static const uint16_t node_u11afu11bc_jamo_seq[] = {
	0x11af,
	0x11bc,
};
static const struct Node node_u11afu11bc = {
	331,
	2,
	node_u11afu11bc_jamo_seq,
	0x11bc,
	0xd7dd,
	0,
	0,
	"u11afu11bc",
};
static const uint16_t node_u11afu11bf_jamo_seq[] = {
	0x11af,
	0x11bf,
};
static const struct Node node_u11afu11bf = {
	332,
	2,
	node_u11afu11bf_jamo_seq,
	0x11bf,
	0x11d8,
	0,
	0,
	"u11afu11bf",
};
static const uint16_t node_u11afu11c0_jamo_seq[] = {
	0x11af,
	0x11c0,
};
static const struct Node node_u11afu11c0 = {
	333,
	2,
	node_u11afu11c0_jamo_seq,
	0x11c0,
	0x11b4,
	0,
	0,
	"u11afu11c0",
};
static const uint16_t node_u11afu11c1_jamo_seq[] = {
	0x11af,
	0x11c1,
};
static const struct Node node_u11afu11c1 = {
	334,
	2,
	node_u11afu11c1_jamo_seq,
	0x11c1,
	0x11b5,
	0,
	0,
	"u11afu11c1",
};
static const uint16_t node_u11afu11c2_jamo_seq[] = {
	0x11af,
	0x11c2,
};
static const struct Node node_u11afu11c2 = {
	335,
	2,
	node_u11afu11c2_jamo_seq,
	0x11c2,
	0x11b6,
	0,
	0,
	"u11afu11c2",
};
static const uint16_t node_u11afu11d8_jamo_seq[] = {
	0x11af,
	0x11d8,
};
static const struct Node node_u11afu11d8 = {
	336,
	2,
	node_u11afu11d8_jamo_seq,
	0x11d8,
	0xd7d7,
	0,
	0,
	"u11afu11d8",
};
static const uint16_t node_u11afu11da_jamo_seq[] = {
	0x11af,
	0x11da,
};
static const struct Node node_u11afu11da = {
	337,
	2,
	node_u11afu11da_jamo_seq,
	0x11da,
	0x11d1,
	0,
	0,
	"u11afu11da",
};
static const uint16_t node_u11afu11dd_jamo_seq[] = {
	0x11af,
	0x11dd,
};
static const struct Node node_u11afu11dd = {
	338,
	2,
	node_u11afu11dd_jamo_seq,
	0x11dd,
	0x11d2,
	0,
	0,
	"u11afu11dd",
};
static const uint16_t node_u11afu11e1_jamo_seq[] = {
	0x11af,
	0x11e1,
};
static const struct Node node_u11afu11e1 = {
	339,
	2,
	node_u11afu11e1_jamo_seq,
	0x11e1,
	0xd7d8,
	0,
	0,
	"u11afu11e1",
};
static const uint16_t node_u11afu11e4_jamo_seq[] = {
	0x11af,
	0x11e4,
};
static const struct Node node_u11afu11e4 = {
	340,
	2,
	node_u11afu11e4_jamo_seq,
	0x11e4,
	0xd7da,
	0,
	0,
	"u11afu11e4",
};
static const uint16_t node_u11afu11e5_jamo_seq[] = {
	0x11af,
	0x11e5,
};
static const struct Node node_u11afu11e5 = {
	341,
	2,
	node_u11afu11e5_jamo_seq,
	0x11e5,
	0x11d4,
	0,
	0,
	"u11afu11e5",
};
static const uint16_t node_u11afu11e6_jamo_seq[] = {
	0x11af,
	0x11e6,
};
static const struct Node node_u11afu11e6 = {
	342,
	2,
	node_u11afu11e6_jamo_seq,
	0x11e6,
	0x11d5,
	0,
	0,
	"u11afu11e6",
};
static const uint16_t node_u11afu11eb_jamo_seq[] = {
	0x11af,
	0x11eb,
};
static const struct Node node_u11afu11eb = {
	343,
	2,
	node_u11afu11eb_jamo_seq,
	0x11eb,
	0x11d7,
	0,
	0,
	"u11afu11eb",
};
static const uint16_t node_u11afu11f0_jamo_seq[] = {
	0x11af,
	0x11f0,
};
static const struct Node node_u11afu11f0 = {
	344,
	2,
	node_u11afu11f0_jamo_seq,
	0x11f0,
	0xd7db,
	0,
	0,
	"u11afu11f0",
};
static const uint16_t node_u11afu11f9u11c2_jamo_seq[] = {
	0x11af,
	0x11f9,
	0x11c2,
};
static const struct Node node_u11afu11f9u11c2 = {
	498,
	3,
	node_u11afu11f9u11c2_jamo_seq,
	0x11c2,
	0xd7dc,
	0,
	0,
	"u11afu11f9u11c2",
};
static const struct Node *node_u11afu11f9_children[] = {
	&node_u11afu11f9u11c2,
};
static const uint16_t node_u11afu11f9_jamo_seq[] = {
	0x11af,
	0x11f9,
};
static const struct Node node_u11afu11f9 = {
	345,
	2,
	node_u11afu11f9_jamo_seq,
	0x11f9,
	0x11d9,
	1,
	node_u11afu11f9_children,
	"u11afu11f9",
};
static const uint16_t node_u11afu11fe_jamo_seq[] = {
	0x11af,
	0x11fe,
};
static const struct Node node_u11afu11fe = {
	346,
	2,
	node_u11afu11fe_jamo_seq,
	0x11fe,
	0xd7d6,
	0,
	0,
	"u11afu11fe",
};
static const uint16_t node_u11afud7e3_jamo_seq[] = {
	0x11af,
	0xd7e3,
};
static const struct Node node_u11afud7e3 = {
	347,
	2,
	node_u11afud7e3_jamo_seq,
	0xd7e3,
	0xd7d9,
	0,
	0,
	"u11afud7e3",
};
static const struct Node *node_u11af_children[] = {
	&node_u11afu11a8,
	&node_u11afu11a9,
	&node_u11afu11aa,
	&node_u11afu11ab,
	&node_u11afu11ae,
	&node_u11afu11af,
	&node_u11afu11b7,
	&node_u11afu11b8,
	&node_u11afu11b9,
	&node_u11afu11ba,
	&node_u11afu11bb,
	&node_u11afu11bc,
	&node_u11afu11bf,
	&node_u11afu11c0,
	&node_u11afu11c1,
	&node_u11afu11c2,
	&node_u11afu11d8,
	&node_u11afu11da,
	&node_u11afu11dd,
	&node_u11afu11e1,
	&node_u11afu11e4,
	&node_u11afu11e5,
	&node_u11afu11e6,
	&node_u11afu11eb,
	&node_u11afu11f0,
	&node_u11afu11f9,
	&node_u11afu11fe,
	&node_u11afud7e3,
};
static const uint16_t node_u11af_jamo_seq[] = {
	0x11af,
};
static const struct Node node_u11af = {
	51,
	1,
	node_u11af_jamo_seq,
	0x11af,
	0,
	28,
	node_u11af_children,
	"u11af",
};
static const uint16_t node_u11b0u11a8_jamo_seq[] = {
	0x11b0,
	0x11a8,
};
static const struct Node node_u11b0u11a8 = {
	348,
	2,
	node_u11b0u11a8_jamo_seq,
	0x11a8,
	0xd7d5,
	0,
	0,
	"u11b0u11a8",
};
static const uint16_t node_u11b0u11ba_jamo_seq[] = {
	0x11b0,
	0x11ba,
};
static const struct Node node_u11b0u11ba = {
	349,
	2,
	node_u11b0u11ba_jamo_seq,
	0x11ba,
	0x11cc,
	0,
	0,
	"u11b0u11ba",
};
static const uint16_t node_u11b0u11c2_jamo_seq[] = {
	0x11b0,
	0x11c2,
};
static const struct Node node_u11b0u11c2 = {
	350,
	2,
	node_u11b0u11c2_jamo_seq,
	0x11c2,
	0xd7d6,
	0,
	0,
	"u11b0u11c2",
};
static const struct Node *node_u11b0_children[] = {
	&node_u11b0u11a8,
	&node_u11b0u11ba,
	&node_u11b0u11c2,
};
static const uint16_t node_u11b0_jamo_seq[] = {
	0x11b0,
};
static const struct Node node_u11b0 = {
	52,
	1,
	node_u11b0_jamo_seq,
	0x11b0,
	0,
	3,
	node_u11b0_children,
	"u11b0",
};
static const uint16_t node_u11b1u11a8_jamo_seq[] = {
	0x11b1,
	0x11a8,
};
static const struct Node node_u11b1u11a8 = {
	351,
	2,
	node_u11b1u11a8_jamo_seq,
	0x11a8,
	0x11d1,
	0,
	0,
	"u11b1u11a8",
};
static const uint16_t node_u11b1u11ba_jamo_seq[] = {
	0x11b1,
	0x11ba,
};
static const struct Node node_u11b1u11ba = {
	352,
	2,
	node_u11b1u11ba_jamo_seq,
	0x11ba,
	0x11d2,
	0,
	0,
	"u11b1u11ba",
};
static const uint16_t node_u11b1u11c2_jamo_seq[] = {
	0x11b1,
	0x11c2,
};
static const struct Node node_u11b1u11c2 = {
	353,
	2,
	node_u11b1u11c2_jamo_seq,
	0x11c2,
	0xd7d8,
	0,
	0,
	"u11b1u11c2",
};
static const struct Node *node_u11b1_children[] = {
	&node_u11b1u11a8,
	&node_u11b1u11ba,
	&node_u11b1u11c2,
};
static const uint16_t node_u11b1_jamo_seq[] = {
	0x11b1,
};
static const struct Node node_u11b1 = {
	53,
	1,
	node_u11b1_jamo_seq,
	0x11b1,
	0,
	3,
	node_u11b1_children,
	"u11b1",
};
static const uint16_t node_u11b2u11ae_jamo_seq[] = {
	0x11b2,
	0x11ae,
};
static const struct Node node_u11b2u11ae = {
	354,
	2,
	node_u11b2u11ae_jamo_seq,
	0x11ae,
	0xd7d9,
	0,
	0,
	"u11b2u11ae",
};
static const uint16_t node_u11b2u11ba_jamo_seq[] = {
	0x11b2,
	0x11ba,
};
static const struct Node node_u11b2u11ba = {
	355,
	2,
	node_u11b2u11ba_jamo_seq,
	0x11ba,
	0x11d3,
	0,
	0,
	"u11b2u11ba",
};
static const uint16_t node_u11b2u11bc_jamo_seq[] = {
	0x11b2,
	0x11bc,
};
static const struct Node node_u11b2u11bc = {
	356,
	2,
	node_u11b2u11bc_jamo_seq,
	0x11bc,
	0x11d5,
	0,
	0,
	"u11b2u11bc",
};
static const uint16_t node_u11b2u11c1_jamo_seq[] = {
	0x11b2,
	0x11c1,
};
static const struct Node node_u11b2u11c1 = {
	357,
	2,
	node_u11b2u11c1_jamo_seq,
	0x11c1,
	0xd7da,
	0,
	0,
	"u11b2u11c1",
};
static const uint16_t node_u11b2u11c2_jamo_seq[] = {
	0x11b2,
	0x11c2,
};
static const struct Node node_u11b2u11c2 = {
	358,
	2,
	node_u11b2u11c2_jamo_seq,
	0x11c2,
	0x11d4,
	0,
	0,
	"u11b2u11c2",
};
static const struct Node *node_u11b2_children[] = {
	&node_u11b2u11ae,
	&node_u11b2u11ba,
	&node_u11b2u11bc,
	&node_u11b2u11c1,
	&node_u11b2u11c2,
};
static const uint16_t node_u11b2_jamo_seq[] = {
	0x11b2,
};
static const struct Node node_u11b2 = {
	54,
	1,
	node_u11b2_jamo_seq,
	0x11b2,
	0,
	5,
	node_u11b2_children,
	"u11b2",
};
static const uint16_t node_u11b3u11ba_jamo_seq[] = {
	0x11b3,
	0x11ba,
};
static const struct Node node_u11b3u11ba = {
	359,
	2,
	node_u11b3u11ba_jamo_seq,
	0x11ba,
	0x11d6,
	0,
	0,
	"u11b3u11ba",
};
static const struct Node *node_u11b3_children[] = {
	&node_u11b3u11ba,
};
static const uint16_t node_u11b3_jamo_seq[] = {
	0x11b3,
};
static const struct Node node_u11b3 = {
	55,
	1,
	node_u11b3_jamo_seq,
	0x11b3,
	0,
	1,
	node_u11b3_children,
	"u11b3",
};
static const uint16_t node_u11b7u11a8_jamo_seq[] = {
	0x11b7,
	0x11a8,
};
static const struct Node node_u11b7u11a8 = {
	360,
	2,
	node_u11b7u11a8_jamo_seq,
	0x11a8,
	0x11da,
	0,
	0,
	"u11b7u11a8",
};
static const uint16_t node_u11b7u11abu11ab_jamo_seq[] = {
	0x11b7,
	0x11ab,
	0x11ab,
};
static const struct Node node_u11b7u11abu11ab = {
	499,
	3,
	node_u11b7u11abu11ab_jamo_seq,
	0x11ab,
	0xd7df,
	0,
	0,
	"u11b7u11abu11ab",
};
static const struct Node *node_u11b7u11ab_children[] = {
	&node_u11b7u11abu11ab,
};
static const uint16_t node_u11b7u11ab_jamo_seq[] = {
	0x11b7,
	0x11ab,
};
static const struct Node node_u11b7u11ab = {
	361,
	2,
	node_u11b7u11ab_jamo_seq,
	0x11ab,
	0xd7de,
	1,
	node_u11b7u11ab_children,
	"u11b7u11ab",
};
static const uint16_t node_u11b7u11af_jamo_seq[] = {
	0x11b7,
	0x11af,
};
static const struct Node node_u11b7u11af = {
	362,
	2,
	node_u11b7u11af_jamo_seq,
	0x11af,
	0x11db,
	0,
	0,
	"u11b7u11af",
};
static const uint16_t node_u11b7u11b7_jamo_seq[] = {
	0x11b7,
	0x11b7,
};
static const struct Node node_u11b7u11b7 = {
	363,
	2,
	node_u11b7u11b7_jamo_seq,
	0x11b7,
	0xd7e0,
	0,
	0,
	"u11b7u11b7",
};
static const uint16_t node_u11b7u11b8u11ba_jamo_seq[] = {
	0x11b7,
	0x11b8,
	0x11ba,
};
static const struct Node node_u11b7u11b8u11ba = {
	500,
	3,
	node_u11b7u11b8u11ba_jamo_seq,
	0x11ba,
	0xd7e1,
	0,
	0,
	"u11b7u11b8u11ba",
};
static const struct Node *node_u11b7u11b8_children[] = {
	&node_u11b7u11b8u11ba,
};
static const uint16_t node_u11b7u11b8_jamo_seq[] = {
	0x11b7,
	0x11b8,
};
static const struct Node node_u11b7u11b8 = {
	364,
	2,
	node_u11b7u11b8_jamo_seq,
	0x11b8,
	0x11dc,
	1,
	node_u11b7u11b8_children,
	"u11b7u11b8",
};
static const uint16_t node_u11b7u11b9_jamo_seq[] = {
	0x11b7,
	0x11b9,
};
static const struct Node node_u11b7u11b9 = {
	365,
	2,
	node_u11b7u11b9_jamo_seq,
	0x11b9,
	0xd7e1,
	0,
	0,
	"u11b7u11b9",
};
static const uint16_t node_u11b7u11bau11ba_jamo_seq[] = {
	0x11b7,
	0x11ba,
	0x11ba,
};
static const struct Node node_u11b7u11bau11ba = {
	501,
	3,
	node_u11b7u11bau11ba_jamo_seq,
	0x11ba,
	0x11de,
	0,
	0,
	"u11b7u11bau11ba",
};
static const struct Node *node_u11b7u11ba_children[] = {
	&node_u11b7u11bau11ba,
};
static const uint16_t node_u11b7u11ba_jamo_seq[] = {
	0x11b7,
	0x11ba,
};
static const struct Node node_u11b7u11ba = {
	366,
	2,
	node_u11b7u11ba_jamo_seq,
	0x11ba,
	0x11dd,
	1,
	node_u11b7u11ba_children,
	"u11b7u11ba",
};
static const uint16_t node_u11b7u11bb_jamo_seq[] = {
	0x11b7,
	0x11bb,
};
static const struct Node node_u11b7u11bb = {
	367,
	2,
	node_u11b7u11bb_jamo_seq,
	0x11bb,
	0x11de,
	0,
	0,
	"u11b7u11bb",
};
static const uint16_t node_u11b7u11bc_jamo_seq[] = {
	0x11b7,
	0x11bc,
};
static const struct Node node_u11b7u11bc = {
	368,
	2,
	node_u11b7u11bc_jamo_seq,
	0x11bc,
	0x11e2,
	0,
	0,
	"u11b7u11bc",
};
static const uint16_t node_u11b7u11bd_jamo_seq[] = {
	0x11b7,
	0x11bd,
};
static const struct Node node_u11b7u11bd = {
	369,
	2,
	node_u11b7u11bd_jamo_seq,
	0x11bd,
	0xd7e2,
	0,
	0,
	"u11b7u11bd",
};
static const uint16_t node_u11b7u11be_jamo_seq[] = {
	0x11b7,
	0x11be,
};
static const struct Node node_u11b7u11be = {
	370,
	2,
	node_u11b7u11be_jamo_seq,
	0x11be,
	0x11e0,
	0,
	0,
	"u11b7u11be",
};
static const uint16_t node_u11b7u11c2_jamo_seq[] = {
	0x11b7,
	0x11c2,
};
static const struct Node node_u11b7u11c2 = {
	371,
	2,
	node_u11b7u11c2_jamo_seq,
	0x11c2,
	0x11e1,
	0,
	0,
	"u11b7u11c2",
};
static const uint16_t node_u11b7u11eb_jamo_seq[] = {
	0x11b7,
	0x11eb,
};
static const struct Node node_u11b7u11eb = {
	372,
	2,
	node_u11b7u11eb_jamo_seq,
	0x11eb,
	0x11df,
	0,
	0,
	"u11b7u11eb",
};
static const uint16_t node_u11b7u11ff_jamo_seq[] = {
	0x11b7,
	0x11ff,
};
static const struct Node node_u11b7u11ff = {
	373,
	2,
	node_u11b7u11ff_jamo_seq,
	0x11ff,
	0xd7df,
	0,
	0,
	"u11b7u11ff",
};
static const struct Node *node_u11b7_children[] = {
	&node_u11b7u11a8,
	&node_u11b7u11ab,
	&node_u11b7u11af,
	&node_u11b7u11b7,
	&node_u11b7u11b8,
	&node_u11b7u11b9,
	&node_u11b7u11ba,
	&node_u11b7u11bb,
	&node_u11b7u11bc,
	&node_u11b7u11bd,
	&node_u11b7u11be,
	&node_u11b7u11c2,
	&node_u11b7u11eb,
	&node_u11b7u11ff,
};
static const uint16_t node_u11b7_jamo_seq[] = {
	0x11b7,
};
static const struct Node node_u11b7 = {
	56,
	1,
	node_u11b7_jamo_seq,
	0x11b7,
	0,
	14,
	node_u11b7_children,
	"u11b7",
};
static const uint16_t node_u11b8u11ae_jamo_seq[] = {
	0x11b8,
	0x11ae,
};
static const struct Node node_u11b8u11ae = {
	374,
	2,
	node_u11b8u11ae_jamo_seq,
	0x11ae,
	0xd7e3,
	0,
	0,
	"u11b8u11ae",
};
static const uint16_t node_u11b8u11afu11c1_jamo_seq[] = {
	0x11b8,
	0x11af,
	0x11c1,
};
static const struct Node node_u11b8u11afu11c1 = {
	502,
	3,
	node_u11b8u11afu11c1_jamo_seq,
	0x11c1,
	0xd7e4,
	0,
	0,
	"u11b8u11afu11c1",
};
static const struct Node *node_u11b8u11af_children[] = {
	&node_u11b8u11afu11c1,
};
static const uint16_t node_u11b8u11af_jamo_seq[] = {
	0x11b8,
	0x11af,
};
static const struct Node node_u11b8u11af = {
	375,
	2,
	node_u11b8u11af_jamo_seq,
	0x11af,
	0x11e3,
	1,
	node_u11b8u11af_children,
	"u11b8u11af",
};
static const uint16_t node_u11b8u11b5_jamo_seq[] = {
	0x11b8,
	0x11b5,
};
static const struct Node node_u11b8u11b5 = {
	376,
	2,
	node_u11b8u11b5_jamo_seq,
	0x11b5,
	0xd7e4,
	0,
	0,
	"u11b8u11b5",
};
static const uint16_t node_u11b8u11b7_jamo_seq[] = {
	0x11b8,
	0x11b7,
};
static const struct Node node_u11b8u11b7 = {
	377,
	2,
	node_u11b8u11b7_jamo_seq,
	0x11b7,
	0xd7e5,
	0,
	0,
	"u11b8u11b7",
};
static const uint16_t node_u11b8u11b8_jamo_seq[] = {
	0x11b8,
	0x11b8,
};
static const struct Node node_u11b8u11b8 = {
	378,
	2,
	node_u11b8u11b8_jamo_seq,
	0x11b8,
	0xd7e6,
	0,
	0,
	"u11b8u11b8",
};
static const uint16_t node_u11b8u11bau11ae_jamo_seq[] = {
	0x11b8,
	0x11ba,
	0x11ae,
};
static const struct Node node_u11b8u11bau11ae = {
	503,
	3,
	node_u11b8u11bau11ae_jamo_seq,
	0x11ae,
	0xd7e7,
	0,
	0,
	"u11b8u11bau11ae",
};
static const struct Node *node_u11b8u11ba_children[] = {
	&node_u11b8u11bau11ae,
};
static const uint16_t node_u11b8u11ba_jamo_seq[] = {
	0x11b8,
	0x11ba,
};
static const struct Node node_u11b8u11ba = {
	379,
	2,
	node_u11b8u11ba_jamo_seq,
	0x11ba,
	0x11b9,
	1,
	node_u11b8u11ba_children,
	"u11b8u11ba",
};
static const uint16_t node_u11b8u11bc_jamo_seq[] = {
	0x11b8,
	0x11bc,
};
static const struct Node node_u11b8u11bc = {
	380,
	2,
	node_u11b8u11bc_jamo_seq,
	0x11bc,
	0x11e6,
	0,
	0,
	"u11b8u11bc",
};
static const uint16_t node_u11b8u11bd_jamo_seq[] = {
	0x11b8,
	0x11bd,
};
static const struct Node node_u11b8u11bd = {
	381,
	2,
	node_u11b8u11bd_jamo_seq,
	0x11bd,
	0xd7e8,
	0,
	0,
	"u11b8u11bd",
};
static const uint16_t node_u11b8u11be_jamo_seq[] = {
	0x11b8,
	0x11be,
};
static const struct Node node_u11b8u11be = {
	382,
	2,
	node_u11b8u11be_jamo_seq,
	0x11be,
	0xd7e9,
	0,
	0,
	"u11b8u11be",
};
static const uint16_t node_u11b8u11c1_jamo_seq[] = {
	0x11b8,
	0x11c1,
};
static const struct Node node_u11b8u11c1 = {
	383,
	2,
	node_u11b8u11c1_jamo_seq,
	0x11c1,
	0x11e4,
	0,
	0,
	"u11b8u11c1",
};
static const uint16_t node_u11b8u11c2_jamo_seq[] = {
	0x11b8,
	0x11c2,
};
static const struct Node node_u11b8u11c2 = {
	384,
	2,
	node_u11b8u11c2_jamo_seq,
	0x11c2,
	0x11e5,
	0,
	0,
	"u11b8u11c2",
};
static const uint16_t node_u11b8u11e8_jamo_seq[] = {
	0x11b8,
	0x11e8,
};
static const struct Node node_u11b8u11e8 = {
	385,
	2,
	node_u11b8u11e8_jamo_seq,
	0x11e8,
	0xd7e7,
	0,
	0,
	"u11b8u11e8",
};
static const struct Node *node_u11b8_children[] = {
	&node_u11b8u11ae,
	&node_u11b8u11af,
	&node_u11b8u11b5,
	&node_u11b8u11b7,
	&node_u11b8u11b8,
	&node_u11b8u11ba,
	&node_u11b8u11bc,
	&node_u11b8u11bd,
	&node_u11b8u11be,
	&node_u11b8u11c1,
	&node_u11b8u11c2,
	&node_u11b8u11e8,
};
static const uint16_t node_u11b8_jamo_seq[] = {
	0x11b8,
};
static const struct Node node_u11b8 = {
	57,
	1,
	node_u11b8_jamo_seq,
	0x11b8,
	0,
	12,
	node_u11b8_children,
	"u11b8",
};
static const uint16_t node_u11b9u11ae_jamo_seq[] = {
	0x11b9,
	0x11ae,
};
static const struct Node node_u11b9u11ae = {
	386,
	2,
	node_u11b9u11ae_jamo_seq,
	0x11ae,
	0xd7e7,
	0,
	0,
	"u11b9u11ae",
};
static const struct Node *node_u11b9_children[] = {
	&node_u11b9u11ae,
};
static const uint16_t node_u11b9_jamo_seq[] = {
	0x11b9,
};
static const struct Node node_u11b9 = {
	58,
	1,
	node_u11b9_jamo_seq,
	0x11b9,
	0,
	1,
	node_u11b9_children,
	"u11b9",
};
static const uint16_t node_u11bau11a8_jamo_seq[] = {
	0x11ba,
	0x11a8,
};
static const struct Node node_u11bau11a8 = {
	387,
	2,
	node_u11bau11a8_jamo_seq,
	0x11a8,
	0x11e7,
	0,
	0,
	"u11bau11a8",
};
static const uint16_t node_u11bau11ae_jamo_seq[] = {
	0x11ba,
	0x11ae,
};
static const struct Node node_u11bau11ae = {
	388,
	2,
	node_u11bau11ae_jamo_seq,
	0x11ae,
	0x11e8,
	0,
	0,
	"u11bau11ae",
};
static const uint16_t node_u11bau11af_jamo_seq[] = {
	0x11ba,
	0x11af,
};
static const struct Node node_u11bau11af = {
	389,
	2,
	node_u11bau11af_jamo_seq,
	0x11af,
	0x11e9,
	0,
	0,
	"u11bau11af",
};
static const uint16_t node_u11bau11b7_jamo_seq[] = {
	0x11ba,
	0x11b7,
};
static const struct Node node_u11bau11b7 = {
	390,
	2,
	node_u11bau11b7_jamo_seq,
	0x11b7,
	0xd7ea,
	0,
	0,
	"u11bau11b7",
};
static const uint16_t node_u11bau11b8u11bc_jamo_seq[] = {
	0x11ba,
	0x11b8,
	0x11bc,
};
static const struct Node node_u11bau11b8u11bc = {
	504,
	3,
	node_u11bau11b8u11bc_jamo_seq,
	0x11bc,
	0xd7eb,
	0,
	0,
	"u11bau11b8u11bc",
};
static const struct Node *node_u11bau11b8_children[] = {
	&node_u11bau11b8u11bc,
};
static const uint16_t node_u11bau11b8_jamo_seq[] = {
	0x11ba,
	0x11b8,
};
static const struct Node node_u11bau11b8 = {
	391,
	2,
	node_u11bau11b8_jamo_seq,
	0x11b8,
	0x11ea,
	1,
	node_u11bau11b8_children,
	"u11bau11b8",
};
static const uint16_t node_u11bau11bau11a8_jamo_seq[] = {
	0x11ba,
	0x11ba,
	0x11a8,
};
static const struct Node node_u11bau11bau11a8 = {
	505,
	3,
	node_u11bau11bau11a8_jamo_seq,
	0x11a8,
	0xd7ec,
	0,
	0,
	"u11bau11bau11a8",
};
static const uint16_t node_u11bau11bau11ae_jamo_seq[] = {
	0x11ba,
	0x11ba,
	0x11ae,
};
static const struct Node node_u11bau11bau11ae = {
	506,
	3,
	node_u11bau11bau11ae_jamo_seq,
	0x11ae,
	0xd7ed,
	0,
	0,
	"u11bau11bau11ae",
};
static const struct Node *node_u11bau11ba_children[] = {
	&node_u11bau11bau11a8,
	&node_u11bau11bau11ae,
};
static const uint16_t node_u11bau11ba_jamo_seq[] = {
	0x11ba,
	0x11ba,
};
static const struct Node node_u11bau11ba = {
	392,
	2,
	node_u11bau11ba_jamo_seq,
	0x11ba,
	0x11bb,
	2,
	node_u11bau11ba_children,
	"u11bau11ba",
};
static const uint16_t node_u11bau11bd_jamo_seq[] = {
	0x11ba,
	0x11bd,
};
static const struct Node node_u11bau11bd = {
	393,
	2,
	node_u11bau11bd_jamo_seq,
	0x11bd,
	0xd7ef,
	0,
	0,
	"u11bau11bd",
};
static const uint16_t node_u11bau11be_jamo_seq[] = {
	0x11ba,
	0x11be,
};
static const struct Node node_u11bau11be = {
	394,
	2,
	node_u11bau11be_jamo_seq,
	0x11be,
	0xd7f0,
	0,
	0,
	"u11bau11be",
};
static const uint16_t node_u11bau11c0_jamo_seq[] = {
	0x11ba,
	0x11c0,
};
static const struct Node node_u11bau11c0 = {
	395,
	2,
	node_u11bau11c0_jamo_seq,
	0x11c0,
	0xd7f1,
	0,
	0,
	"u11bau11c0",
};
static const uint16_t node_u11bau11c2_jamo_seq[] = {
	0x11ba,
	0x11c2,
};
static const struct Node node_u11bau11c2 = {
	396,
	2,
	node_u11bau11c2_jamo_seq,
	0x11c2,
	0xd7f2,
	0,
	0,
	"u11bau11c2",
};
static const uint16_t node_u11bau11e6_jamo_seq[] = {
	0x11ba,
	0x11e6,
};
static const struct Node node_u11bau11e6 = {
	397,
	2,
	node_u11bau11e6_jamo_seq,
	0x11e6,
	0xd7eb,
	0,
	0,
	"u11bau11e6",
};
static const uint16_t node_u11bau11e7_jamo_seq[] = {
	0x11ba,
	0x11e7,
};
static const struct Node node_u11bau11e7 = {
	398,
	2,
	node_u11bau11e7_jamo_seq,
	0x11e7,
	0xd7ec,
	0,
	0,
	"u11bau11e7",
};
static const uint16_t node_u11bau11e8_jamo_seq[] = {
	0x11ba,
	0x11e8,
};
static const struct Node node_u11bau11e8 = {
	399,
	2,
	node_u11bau11e8_jamo_seq,
	0x11e8,
	0xd7ed,
	0,
	0,
	"u11bau11e8",
};
static const uint16_t node_u11bau11eb_jamo_seq[] = {
	0x11ba,
	0x11eb,
};
static const struct Node node_u11bau11eb = {
	400,
	2,
	node_u11bau11eb_jamo_seq,
	0x11eb,
	0xd7ee,
	0,
	0,
	"u11bau11eb",
};
static const struct Node *node_u11ba_children[] = {
	&node_u11bau11a8,
	&node_u11bau11ae,
	&node_u11bau11af,
	&node_u11bau11b7,
	&node_u11bau11b8,
	&node_u11bau11ba,
	&node_u11bau11bd,
	&node_u11bau11be,
	&node_u11bau11c0,
	&node_u11bau11c2,
	&node_u11bau11e6,
	&node_u11bau11e7,
	&node_u11bau11e8,
	&node_u11bau11eb,
};
static const uint16_t node_u11ba_jamo_seq[] = {
	0x11ba,
};
static const struct Node node_u11ba = {
	59,
	1,
	node_u11ba_jamo_seq,
	0x11ba,
	0,
	14,
	node_u11ba_children,
	"u11ba",
};
static const uint16_t node_u11bbu11a8_jamo_seq[] = {
	0x11bb,
	0x11a8,
};
static const struct Node node_u11bbu11a8 = {
	401,
	2,
	node_u11bbu11a8_jamo_seq,
	0x11a8,
	0xd7ec,
	0,
	0,
	"u11bbu11a8",
};
static const uint16_t node_u11bbu11ae_jamo_seq[] = {
	0x11bb,
	0x11ae,
};
static const struct Node node_u11bbu11ae = {
	402,
	2,
	node_u11bbu11ae_jamo_seq,
	0x11ae,
	0xd7ed,
	0,
	0,
	"u11bbu11ae",
};
static const struct Node *node_u11bb_children[] = {
	&node_u11bbu11a8,
	&node_u11bbu11ae,
};
static const uint16_t node_u11bb_jamo_seq[] = {
	0x11bb,
};
static const struct Node node_u11bb = {
	60,
	1,
	node_u11bb_jamo_seq,
	0x11bb,
	0,
	2,
	node_u11bb_children,
	"u11bb",
};
static const uint16_t node_u11bcu11a8u11a8_jamo_seq[] = {
	0x11bc,
	0x11a8,
	0x11a8,
};
static const struct Node node_u11bcu11a8u11a8 = {
	507,
	3,
	node_u11bcu11a8u11a8_jamo_seq,
	0x11a8,
	0x11ed,
	0,
	0,
	"u11bcu11a8u11a8",
};
static const struct Node *node_u11bcu11a8_children[] = {
	&node_u11bcu11a8u11a8,
};
static const uint16_t node_u11bcu11a8_jamo_seq[] = {
	0x11bc,
	0x11a8,
};
static const struct Node node_u11bcu11a8 = {
	403,
	2,
	node_u11bcu11a8_jamo_seq,
	0x11a8,
	0x11ec,
	1,
	node_u11bcu11a8_children,
	"u11bcu11a8",
};
static const uint16_t node_u11bcu11a9_jamo_seq[] = {
	0x11bc,
	0x11a9,
};
static const struct Node node_u11bcu11a9 = {
	404,
	2,
	node_u11bcu11a9_jamo_seq,
	0x11a9,
	0x11ed,
	0,
	0,
	"u11bcu11a9",
};
static const uint16_t node_u11bcu11bc_jamo_seq[] = {
	0x11bc,
	0x11bc,
};
static const struct Node node_u11bcu11bc = {
	405,
	2,
	node_u11bcu11bc_jamo_seq,
	0x11bc,
	0x11ee,
	0,
	0,
	"u11bcu11bc",
};
static const uint16_t node_u11bcu11bf_jamo_seq[] = {
	0x11bc,
	0x11bf,
};
static const struct Node node_u11bcu11bf = {
	406,
	2,
	node_u11bcu11bf_jamo_seq,
	0x11bf,
	0x11ef,
	0,
	0,
	"u11bcu11bf",
};
static const struct Node *node_u11bc_children[] = {
	&node_u11bcu11a8,
	&node_u11bcu11a9,
	&node_u11bcu11bc,
	&node_u11bcu11bf,
};
static const uint16_t node_u11bc_jamo_seq[] = {
	0x11bc,
};
static const struct Node node_u11bc = {
	61,
	1,
	node_u11bc_jamo_seq,
	0x11bc,
	0,
	4,
	node_u11bc_children,
	"u11bc",
};
static const uint16_t node_u11bdu11b8u11b8_jamo_seq[] = {
	0x11bd,
	0x11b8,
	0x11b8,
};
static const struct Node node_u11bdu11b8u11b8 = {
	508,
	3,
	node_u11bdu11b8u11b8_jamo_seq,
	0x11b8,
	0xd7f8,
	0,
	0,
	"u11bdu11b8u11b8",
};
static const struct Node *node_u11bdu11b8_children[] = {
	&node_u11bdu11b8u11b8,
};
static const uint16_t node_u11bdu11b8_jamo_seq[] = {
	0x11bd,
	0x11b8,
};
static const struct Node node_u11bdu11b8 = {
	407,
	2,
	node_u11bdu11b8_jamo_seq,
	0x11b8,
	0xd7f7,
	1,
	node_u11bdu11b8_children,
	"u11bdu11b8",
};
static const uint16_t node_u11bdu11bd_jamo_seq[] = {
	0x11bd,
	0x11bd,
};
static const struct Node node_u11bdu11bd = {
	408,
	2,
	node_u11bdu11bd_jamo_seq,
	0x11bd,
	0xd7f9,
	0,
	0,
	"u11bdu11bd",
};
static const uint16_t node_u11bdud7e6_jamo_seq[] = {
	0x11bd,
	0xd7e6,
};
static const struct Node node_u11bdud7e6 = {
	409,
	2,
	node_u11bdud7e6_jamo_seq,
	0xd7e6,
	0xd7f8,
	0,
	0,
	"u11bdud7e6",
};
static const struct Node *node_u11bd_children[] = {
	&node_u11bdu11b8,
	&node_u11bdu11bd,
	&node_u11bdud7e6,
};
static const uint16_t node_u11bd_jamo_seq[] = {
	0x11bd,
};
static const struct Node node_u11bd = {
	62,
	1,
	node_u11bd_jamo_seq,
	0x11bd,
	0,
	3,
	node_u11bd_children,
	"u11bd",
};
static const uint16_t node_u11c1u11b8_jamo_seq[] = {
	0x11c1,
	0x11b8,
};
static const struct Node node_u11c1u11b8 = {
	410,
	2,
	node_u11c1u11b8_jamo_seq,
	0x11b8,
	0x11f3,
	0,
	0,
	"u11c1u11b8",
};
static const uint16_t node_u11c1u11ba_jamo_seq[] = {
	0x11c1,
	0x11ba,
};
static const struct Node node_u11c1u11ba = {
	411,
	2,
	node_u11c1u11ba_jamo_seq,
	0x11ba,
	0xd7fa,
	0,
	0,
	"u11c1u11ba",
};
static const uint16_t node_u11c1u11bc_jamo_seq[] = {
	0x11c1,
	0x11bc,
};
static const struct Node node_u11c1u11bc = {
	412,
	2,
	node_u11c1u11bc_jamo_seq,
	0x11bc,
	0x11f4,
	0,
	0,
	"u11c1u11bc",
};
static const uint16_t node_u11c1u11c0_jamo_seq[] = {
	0x11c1,
	0x11c0,
};
static const struct Node node_u11c1u11c0 = {
	413,
	2,
	node_u11c1u11c0_jamo_seq,
	0x11c0,
	0xd7fb,
	0,
	0,
	"u11c1u11c0",
};
static const struct Node *node_u11c1_children[] = {
	&node_u11c1u11b8,
	&node_u11c1u11ba,
	&node_u11c1u11bc,
	&node_u11c1u11c0,
};
static const uint16_t node_u11c1_jamo_seq[] = {
	0x11c1,
};
static const struct Node node_u11c1 = {
	63,
	1,
	node_u11c1_jamo_seq,
	0x11c1,
	0,
	4,
	node_u11c1_children,
	"u11c1",
};
static const uint16_t node_u11c2u11ab_jamo_seq[] = {
	0x11c2,
	0x11ab,
};
static const struct Node node_u11c2u11ab = {
	414,
	2,
	node_u11c2u11ab_jamo_seq,
	0x11ab,
	0x11f5,
	0,
	0,
	"u11c2u11ab",
};
static const uint16_t node_u11c2u11af_jamo_seq[] = {
	0x11c2,
	0x11af,
};
static const struct Node node_u11c2u11af = {
	415,
	2,
	node_u11c2u11af_jamo_seq,
	0x11af,
	0x11f6,
	0,
	0,
	"u11c2u11af",
};
static const uint16_t node_u11c2u11b7_jamo_seq[] = {
	0x11c2,
	0x11b7,
};
static const struct Node node_u11c2u11b7 = {
	416,
	2,
	node_u11c2u11b7_jamo_seq,
	0x11b7,
	0x11f7,
	0,
	0,
	"u11c2u11b7",
};
static const uint16_t node_u11c2u11b8_jamo_seq[] = {
	0x11c2,
	0x11b8,
};
static const struct Node node_u11c2u11b8 = {
	417,
	2,
	node_u11c2u11b8_jamo_seq,
	0x11b8,
	0x11f8,
	0,
	0,
	"u11c2u11b8",
};
static const struct Node *node_u11c2_children[] = {
	&node_u11c2u11ab,
	&node_u11c2u11af,
	&node_u11c2u11b7,
	&node_u11c2u11b8,
};
static const uint16_t node_u11c2_jamo_seq[] = {
	0x11c2,
};
static const struct Node node_u11c2 = {
	64,
	1,
	node_u11c2_jamo_seq,
	0x11c2,
	0,
	4,
	node_u11c2_children,
	"u11c2",
};
static const uint16_t node_u11ceu11c2_jamo_seq[] = {
	0x11ce,
	0x11c2,
};
static const struct Node node_u11ceu11c2 = {
	418,
	2,
	node_u11ceu11c2_jamo_seq,
	0x11c2,
	0x11cf,
	0,
	0,
	"u11ceu11c2",
};
static const struct Node *node_u11ce_children[] = {
	&node_u11ceu11c2,
};
static const uint16_t node_u11ce_jamo_seq[] = {
	0x11ce,
};
static const struct Node node_u11ce = {
	65,
	1,
	node_u11ce_jamo_seq,
	0x11ce,
	0,
	1,
	node_u11ce_children,
	"u11ce",
};
static const uint16_t node_u11d0u11bf_jamo_seq[] = {
	0x11d0,
	0x11bf,
};
static const struct Node node_u11d0u11bf = {
	419,
	2,
	node_u11d0u11bf_jamo_seq,
	0x11bf,
	0xd7d7,
	0,
	0,
	"u11d0u11bf",
};
static const struct Node *node_u11d0_children[] = {
	&node_u11d0u11bf,
};
static const uint16_t node_u11d0_jamo_seq[] = {
	0x11d0,
};
static const struct Node node_u11d0 = {
	66,
	1,
	node_u11d0_jamo_seq,
	0x11d0,
	0,
	1,
	node_u11d0_children,
	"u11d0",
};
static const uint16_t node_u11d9u11c2_jamo_seq[] = {
	0x11d9,
	0x11c2,
};
static const struct Node node_u11d9u11c2 = {
	420,
	2,
	node_u11d9u11c2_jamo_seq,
	0x11c2,
	0xd7dc,
	0,
	0,
	"u11d9u11c2",
};
static const struct Node *node_u11d9_children[] = {
	&node_u11d9u11c2,
};
static const uint16_t node_u11d9_jamo_seq[] = {
	0x11d9,
};
static const struct Node node_u11d9 = {
	67,
	1,
	node_u11d9_jamo_seq,
	0x11d9,
	0,
	1,
	node_u11d9_children,
	"u11d9",
};
static const uint16_t node_u11dcu11ba_jamo_seq[] = {
	0x11dc,
	0x11ba,
};
static const struct Node node_u11dcu11ba = {
	421,
	2,
	node_u11dcu11ba_jamo_seq,
	0x11ba,
	0xd7e1,
	0,
	0,
	"u11dcu11ba",
};
static const struct Node *node_u11dc_children[] = {
	&node_u11dcu11ba,
};
static const uint16_t node_u11dc_jamo_seq[] = {
	0x11dc,
};
static const struct Node node_u11dc = {
	68,
	1,
	node_u11dc_jamo_seq,
	0x11dc,
	0,
	1,
	node_u11dc_children,
	"u11dc",
};
static const uint16_t node_u11ddu11ba_jamo_seq[] = {
	0x11dd,
	0x11ba,
};
static const struct Node node_u11ddu11ba = {
	422,
	2,
	node_u11ddu11ba_jamo_seq,
	0x11ba,
	0x11de,
	0,
	0,
	"u11ddu11ba",
};
static const struct Node *node_u11dd_children[] = {
	&node_u11ddu11ba,
};
static const uint16_t node_u11dd_jamo_seq[] = {
	0x11dd,
};
static const struct Node node_u11dd = {
	69,
	1,
	node_u11dd_jamo_seq,
	0x11dd,
	0,
	1,
	node_u11dd_children,
	"u11dd",
};
static const uint16_t node_u11e3u11c1_jamo_seq[] = {
	0x11e3,
	0x11c1,
};
static const struct Node node_u11e3u11c1 = {
	423,
	2,
	node_u11e3u11c1_jamo_seq,
	0x11c1,
	0xd7e4,
	0,
	0,
	"u11e3u11c1",
};
static const struct Node *node_u11e3_children[] = {
	&node_u11e3u11c1,
};
static const uint16_t node_u11e3_jamo_seq[] = {
	0x11e3,
};
static const struct Node node_u11e3 = {
	70,
	1,
	node_u11e3_jamo_seq,
	0x11e3,
	0,
	1,
	node_u11e3_children,
	"u11e3",
};
static const uint16_t node_u11eau11bc_jamo_seq[] = {
	0x11ea,
	0x11bc,
};
static const struct Node node_u11eau11bc = {
	424,
	2,
	node_u11eau11bc_jamo_seq,
	0x11bc,
	0xd7eb,
	0,
	0,
	"u11eau11bc",
};
static const struct Node *node_u11ea_children[] = {
	&node_u11eau11bc,
};
static const uint16_t node_u11ea_jamo_seq[] = {
	0x11ea,
};
static const struct Node node_u11ea = {
	71,
	1,
	node_u11ea_jamo_seq,
	0x11ea,
	0,
	1,
	node_u11ea_children,
	"u11ea",
};
static const uint16_t node_u11ebu11b8u11bc_jamo_seq[] = {
	0x11eb,
	0x11b8,
	0x11bc,
};
static const struct Node node_u11ebu11b8u11bc = {
	509,
	3,
	node_u11ebu11b8u11bc_jamo_seq,
	0x11bc,
	0xd7f4,
	0,
	0,
	"u11ebu11b8u11bc",
};
static const struct Node *node_u11ebu11b8_children[] = {
	&node_u11ebu11b8u11bc,
};
static const uint16_t node_u11ebu11b8_jamo_seq[] = {
	0x11eb,
	0x11b8,
};
static const struct Node node_u11ebu11b8 = {
	425,
	2,
	node_u11ebu11b8_jamo_seq,
	0x11b8,
	0xd7f3,
	1,
	node_u11ebu11b8_children,
	"u11ebu11b8",
};
static const uint16_t node_u11ebu11e6_jamo_seq[] = {
	0x11eb,
	0x11e6,
};
static const struct Node node_u11ebu11e6 = {
	426,
	2,
	node_u11ebu11e6_jamo_seq,
	0x11e6,
	0xd7f4,
	0,
	0,
	"u11ebu11e6",
};
static const struct Node *node_u11eb_children[] = {
	&node_u11ebu11b8,
	&node_u11ebu11e6,
};
static const uint16_t node_u11eb_jamo_seq[] = {
	0x11eb,
};
static const struct Node node_u11eb = {
	72,
	1,
	node_u11eb_jamo_seq,
	0x11eb,
	0,
	2,
	node_u11eb_children,
	"u11eb",
};
static const uint16_t node_u11ecu11a8_jamo_seq[] = {
	0x11ec,
	0x11a8,
};
static const struct Node node_u11ecu11a8 = {
	427,
	2,
	node_u11ecu11a8_jamo_seq,
	0x11a8,
	0x11ed,
	0,
	0,
	"u11ecu11a8",
};
static const struct Node *node_u11ec_children[] = {
	&node_u11ecu11a8,
};
static const uint16_t node_u11ec_jamo_seq[] = {
	0x11ec,
};
static const struct Node node_u11ec = {
	73,
	1,
	node_u11ec_jamo_seq,
	0x11ec,
	0,
	1,
	node_u11ec_children,
	"u11ec",
};
static const uint16_t node_u11f0u11a8u11a8_jamo_seq[] = {
	0x11f0,
	0x11a8,
	0x11a8,
};
static const struct Node node_u11f0u11a8u11a8 = {
	510,
	3,
	node_u11f0u11a8u11a8_jamo_seq,
	0x11a8,
	0x11ed,
	0,
	0,
	"u11f0u11a8u11a8",
};
static const struct Node *node_u11f0u11a8_children[] = {
	&node_u11f0u11a8u11a8,
};
static const uint16_t node_u11f0u11a8_jamo_seq[] = {
	0x11f0,
	0x11a8,
};
static const struct Node node_u11f0u11a8 = {
	428,
	2,
	node_u11f0u11a8_jamo_seq,
	0x11a8,
	0x11ec,
	1,
	node_u11f0u11a8_children,
	"u11f0u11a8",
};
static const uint16_t node_u11f0u11a9_jamo_seq[] = {
	0x11f0,
	0x11a9,
};
static const struct Node node_u11f0u11a9 = {
	429,
	2,
	node_u11f0u11a9_jamo_seq,
	0x11a9,
	0x11ed,
	0,
	0,
	"u11f0u11a9",
};
static const uint16_t node_u11f0u11b7_jamo_seq[] = {
	0x11f0,
	0x11b7,
};
static const struct Node node_u11f0u11b7 = {
	430,
	2,
	node_u11f0u11b7_jamo_seq,
	0x11b7,
	0xd7f5,
	0,
	0,
	"u11f0u11b7",
};
static const uint16_t node_u11f0u11ba_jamo_seq[] = {
	0x11f0,
	0x11ba,
};
static const struct Node node_u11f0u11ba = {
	431,
	2,
	node_u11f0u11ba_jamo_seq,
	0x11ba,
	0x11f1,
	0,
	0,
	"u11f0u11ba",
};
static const uint16_t node_u11f0u11bf_jamo_seq[] = {
	0x11f0,
	0x11bf,
};
static const struct Node node_u11f0u11bf = {
	432,
	2,
	node_u11f0u11bf_jamo_seq,
	0x11bf,
	0x11ef,
	0,
	0,
	"u11f0u11bf",
};
static const uint16_t node_u11f0u11c2_jamo_seq[] = {
	0x11f0,
	0x11c2,
};
static const struct Node node_u11f0u11c2 = {
	433,
	2,
	node_u11f0u11c2_jamo_seq,
	0x11c2,
	0xd7f6,
	0,
	0,
	"u11f0u11c2",
};
static const uint16_t node_u11f0u11eb_jamo_seq[] = {
	0x11f0,
	0x11eb,
};
static const struct Node node_u11f0u11eb = {
	434,
	2,
	node_u11f0u11eb_jamo_seq,
	0x11eb,
	0x11f2,
	0,
	0,
	"u11f0u11eb",
};
static const uint16_t node_u11f0u11f0_jamo_seq[] = {
	0x11f0,
	0x11f0,
};
static const struct Node node_u11f0u11f0 = {
	435,
	2,
	node_u11f0u11f0_jamo_seq,
	0x11f0,
	0x11ee,
	0,
	0,
	"u11f0u11f0",
};
static const struct Node *node_u11f0_children[] = {
	&node_u11f0u11a8,
	&node_u11f0u11a9,
	&node_u11f0u11b7,
	&node_u11f0u11ba,
	&node_u11f0u11bf,
	&node_u11f0u11c2,
	&node_u11f0u11eb,
	&node_u11f0u11f0,
};
static const uint16_t node_u11f0_jamo_seq[] = {
	0x11f0,
};
static const struct Node node_u11f0 = {
	74,
	1,
	node_u11f0_jamo_seq,
	0x11f0,
	0,
	8,
	node_u11f0_children,
	"u11f0",
};
static const uint16_t node_ua964u1100_jamo_seq[] = {
	0xa964,
	0x1100,
};
static const struct Node node_ua964u1100 = {
	436,
	2,
	node_ua964u1100_jamo_seq,
	0x1100,
	0xa965,
	0,
	0,
	"ua964u1100",
};
static const struct Node *node_ua964_children[] = {
	&node_ua964u1100,
};
static const uint16_t node_ua964_jamo_seq[] = {
	0xa964,
};
static const struct Node node_ua964 = {
	75,
	1,
	node_ua964_jamo_seq,
	0xa964,
	0,
	1,
	node_ua964_children,
	"ua964",
};
static const uint16_t node_ua966u1103_jamo_seq[] = {
	0xa966,
	0x1103,
};
static const struct Node node_ua966u1103 = {
	437,
	2,
	node_ua966u1103_jamo_seq,
	0x1103,
	0xa967,
	0,
	0,
	"ua966u1103",
};
static const struct Node *node_ua966_children[] = {
	&node_ua966u1103,
};
static const uint16_t node_ua966_jamo_seq[] = {
	0xa966,
};
static const struct Node node_ua966 = {
	76,
	1,
	node_ua966_jamo_seq,
	0xa966,
	0,
	1,
	node_ua966_children,
	"ua966",
};
static const uint16_t node_ua969u1107_jamo_seq[] = {
	0xa969,
	0x1107,
};
static const struct Node node_ua969u1107 = {
	438,
	2,
	node_ua969u1107_jamo_seq,
	0x1107,
	0xa96a,
	0,
	0,
	"ua969u1107",
};
static const struct Node *node_ua969_children[] = {
	&node_ua969u1107,
};
static const uint16_t node_ua969_jamo_seq[] = {
	0xa969,
};
static const struct Node node_ua969 = {
	77,
	1,
	node_ua969_jamo_seq,
	0xa969,
	0,
	1,
	node_ua969_children,
	"ua969",
};
static const uint16_t node_ud7cdu11b8_jamo_seq[] = {
	0xd7cd,
	0x11b8,
};
static const struct Node node_ud7cdu11b8 = {
	439,
	2,
	node_ud7cdu11b8_jamo_seq,
	0x11b8,
	0xd7ce,
	0,
	0,
	"ud7cdu11b8",
};
static const struct Node *node_ud7cd_children[] = {
	&node_ud7cdu11b8,
};
static const uint16_t node_ud7cd_jamo_seq[] = {
	0xd7cd,
};
static const struct Node node_ud7cd = {
	78,
	1,
	node_ud7cd_jamo_seq,
	0xd7cd,
	0,
	1,
	node_ud7cd_children,
	"ud7cd",
};
static const uint16_t node_ud7d0u11a8_jamo_seq[] = {
	0xd7d0,
	0x11a8,
};
static const struct Node node_ud7d0u11a8 = {
	440,
	2,
	node_ud7d0u11a8_jamo_seq,
	0x11a8,
	0xd7d1,
	0,
	0,
	"ud7d0u11a8",
};
static const struct Node *node_ud7d0_children[] = {
	&node_ud7d0u11a8,
};
static const uint16_t node_ud7d0_jamo_seq[] = {
	0xd7d0,
};
static const struct Node node_ud7d0 = {
	79,
	1,
	node_ud7d0_jamo_seq,
	0xd7d0,
	0,
	1,
	node_ud7d0_children,
	"ud7d0",
};
static const uint16_t node_ud7deu11ab_jamo_seq[] = {
	0xd7de,
	0x11ab,
};
static const struct Node node_ud7deu11ab = {
	441,
	2,
	node_ud7deu11ab_jamo_seq,
	0x11ab,
	0xd7df,
	0,
	0,
	"ud7deu11ab",
};
static const struct Node *node_ud7de_children[] = {
	&node_ud7deu11ab,
};
static const uint16_t node_ud7de_jamo_seq[] = {
	0xd7de,
};
static const struct Node node_ud7de = {
	80,
	1,
	node_ud7de_jamo_seq,
	0xd7de,
	0,
	1,
	node_ud7de_children,
	"ud7de",
};
static const uint16_t node_ud7f3u11bc_jamo_seq[] = {
	0xd7f3,
	0x11bc,
};
static const struct Node node_ud7f3u11bc = {
	442,
	2,
	node_ud7f3u11bc_jamo_seq,
	0x11bc,
	0xd7f4,
	0,
	0,
	"ud7f3u11bc",
};
static const struct Node *node_ud7f3_children[] = {
	&node_ud7f3u11bc,
};
static const uint16_t node_ud7f3_jamo_seq[] = {
	0xd7f3,
};
static const struct Node node_ud7f3 = {
	81,
	1,
	node_ud7f3_jamo_seq,
	0xd7f3,
	0,
	1,
	node_ud7f3_children,
	"ud7f3",
};
static const uint16_t node_ud7f7u11b8_jamo_seq[] = {
	0xd7f7,
	0x11b8,
};
static const struct Node node_ud7f7u11b8 = {
	443,
	2,
	node_ud7f7u11b8_jamo_seq,
	0x11b8,
	0xd7f8,
	0,
	0,
	"ud7f7u11b8",
};
static const struct Node *node_ud7f7_children[] = {
	&node_ud7f7u11b8,
};
static const uint16_t node_ud7f7_jamo_seq[] = {
	0xd7f7,
};
static const struct Node node_ud7f7 = {
	82,
	1,
	node_ud7f7_jamo_seq,
	0xd7f7,
	0,
	1,
	node_ud7f7_children,
	"ud7f7",
};
static const struct Node *node_root_children[] = {
	&node_u1100,
	&node_u1102,
	&node_u1103,
	&node_u1105,
	&node_u1106,
	&node_u1107,
	&node_u1108,
	&node_u1109,
	&node_u110a,
	&node_u110b,
	&node_u110c,
	&node_u110d,
	&node_u110e,
	&node_u1110,
	&node_u1111,
	&node_u1112,
	&node_u1121,
	&node_u1132,
	&node_u113c,
	&node_u113e,
	&node_u114e,
	&node_u1150,
	&node_u1159,
	&node_u1161,
	&node_u1163,
	&node_u1165,
	&node_u1167,
	&node_u1169,
	&node_u116a,
	&node_u116d,
	&node_u116e,
	&node_u116f,
	&node_u1171,
	&node_u1172,
	&node_u1173,
	&node_u1174,
	&node_u1175,
	&node_u117f,
	&node_u1182,
	&node_u1184,
	&node_u1189,
	&node_u118f,
	&node_u1191,
	&node_u1199,
	&node_u119a,
	&node_u119e,
	&node_u11a8,
	&node_u11aa,
	&node_u11ab,
	&node_u11ae,
	&node_u11af,
	&node_u11b0,
	&node_u11b1,
	&node_u11b2,
	&node_u11b3,
	&node_u11b7,
	&node_u11b8,
	&node_u11b9,
	&node_u11ba,
	&node_u11bb,
	&node_u11bc,
	&node_u11bd,
	&node_u11c1,
	&node_u11c2,
	&node_u11ce,
	&node_u11d0,
	&node_u11d9,
	&node_u11dc,
	&node_u11dd,
	&node_u11e3,
	&node_u11ea,
	&node_u11eb,
	&node_u11ec,
	&node_u11f0,
	&node_ua964,
	&node_ua966,
	&node_ua969,
	&node_ud7cd,
	&node_ud7d0,
	&node_ud7de,
	&node_ud7f3,
	&node_ud7f7,
};
static const struct Node node_root = {
	0,
	0,
	0,
	0,
	0,
	82,
	node_root_children,
	"root",
};

static const struct Node* nodelist[] = {
	&node_root,
	&node_u1100,
	&node_u1102,
	&node_u1103,
	&node_u1105,
	&node_u1106,
	&node_u1107,
	&node_u1108,
	&node_u1109,
	&node_u110a,
	&node_u110b,
	&node_u110c,
	&node_u110d,
	&node_u110e,
	&node_u1110,
	&node_u1111,
	&node_u1112,
	&node_u1121,
	&node_u1132,
	&node_u113c,
	&node_u113e,
	&node_u114e,
	&node_u1150,
	&node_u1159,
	&node_u1161,
	&node_u1163,
	&node_u1165,
	&node_u1167,
	&node_u1169,
	&node_u116a,
	&node_u116d,
	&node_u116e,
	&node_u116f,
	&node_u1171,
	&node_u1172,
	&node_u1173,
	&node_u1174,
	&node_u1175,
	&node_u117f,
	&node_u1182,
	&node_u1184,
	&node_u1189,
	&node_u118f,
	&node_u1191,
	&node_u1199,
	&node_u119a,
	&node_u119e,
	&node_u11a8,
	&node_u11aa,
	&node_u11ab,
	&node_u11ae,
	&node_u11af,
	&node_u11b0,
	&node_u11b1,
	&node_u11b2,
	&node_u11b3,
	&node_u11b7,
	&node_u11b8,
	&node_u11b9,
	&node_u11ba,
	&node_u11bb,
	&node_u11bc,
	&node_u11bd,
	&node_u11c1,
	&node_u11c2,
	&node_u11ce,
	&node_u11d0,
	&node_u11d9,
	&node_u11dc,
	&node_u11dd,
	&node_u11e3,
	&node_u11ea,
	&node_u11eb,
	&node_u11ec,
	&node_u11f0,
	&node_ua964,
	&node_ua966,
	&node_ua969,
	&node_ud7cd,
	&node_ud7d0,
	&node_ud7de,
	&node_ud7f3,
	&node_ud7f7,
	&node_u1100u1100,
	&node_u1100u1103,
	&node_u1102u1100,
	&node_u1102u1102,
	&node_u1102u1103,
	&node_u1102u1107,
	&node_u1102u1109,
	&node_u1102u110c,
	&node_u1102u1112,
	&node_u1103u1100,
	&node_u1103u1103,
	&node_u1103u1105,
	&node_u1103u1106,
	&node_u1103u1107,
	&node_u1103u1109,
	&node_u1103u110c,
	&node_u1105u1100,
	&node_u1105u1101,
	&node_u1105u1102,
	&node_u1105u1103,
	&node_u1105u1104,
	&node_u1105u1105,
	&node_u1105u1106,
	&node_u1105u1107,
	&node_u1105u1108,
	&node_u1105u1109,
	&node_u1105u110b,
	&node_u1105u110c,
	&node_u1105u110f,
	&node_u1105u1112,
	&node_u1105u112b,
	&node_u1106u1100,
	&node_u1106u1103,
	&node_u1106u1107,
	&node_u1106u1109,
	&node_u1106u110b,
	&node_u1107u1100,
	&node_u1107u1102,
	&node_u1107u1103,
	&node_u1107u1107,
	&node_u1107u1109,
	&node_u1107u110a,
	&node_u1107u110b,
	&node_u1107u110c,
	&node_u1107u110e,
	&node_u1107u110f,
	&node_u1107u1110,
	&node_u1107u1111,
	&node_u1107u1112,
	&node_u1107u112b,
	&node_u1107u112d,
	&node_u1107u112f,
	&node_u1107u1132,
	&node_u1107u1136,
	&node_u1107u1139,
	&node_u1108u110b,
	&node_u1109u1100,
	&node_u1109u1102,
	&node_u1109u1103,
	&node_u1109u1105,
	&node_u1109u1106,
	&node_u1109u1107,
	&node_u1109u1109,
	&node_u1109u110a,
	&node_u1109u110b,
	&node_u1109u110c,
	&node_u1109u110e,
	&node_u1109u110f,
	&node_u1109u1110,
	&node_u1109u1111,
	&node_u1109u1112,
	&node_u1109u111e,
	&node_u1109u1132,
	&node_u110au1107,
	&node_u110au1109,
	&node_u110bu1100,
	&node_u110bu1103,
	&node_u110bu1105,
	&node_u110bu1106,
	&node_u110bu1107,
	&node_u110bu1109,
	&node_u110bu110b,
	&node_u110bu110c,
	&node_u110bu110e,
	&node_u110bu1110,
	&node_u110bu1111,
	&node_u110bu1112,
	&node_u110bu1140,
	&node_u110cu110b,
	&node_u110cu110c,
	&node_u110du1112,
	&node_u110eu110f,
	&node_u110eu1112,
	&node_u1110u1110,
	&node_u1111u1107,
	&node_u1111u110b,
	&node_u1111u1112,
	&node_u1112u1109,
	&node_u1112u1112,
	&node_u1121u1100,
	&node_u1121u1103,
	&node_u1121u1107,
	&node_u1121u1109,
	&node_u1121u110c,
	&node_u1121u1110,
	&node_u1132u1100,
	&node_u113cu113c,
	&node_u113eu113e,
	&node_u114eu114e,
	&node_u1150u1150,
	&node_u1159u1159,
	&node_u1161u1169,
	&node_u1161u116e,
	&node_u1161u1173,
	&node_u1161u1175,
	&node_u1163u1169,
	&node_u1163u116d,
	&node_u1163u116e,
	&node_u1163u1175,
	&node_u1165u1169,
	&node_u1165u116e,
	&node_u1165u1173,
	&node_u1165u1175,
	&node_u1167u1163,
	&node_u1167u1169,
	&node_u1167u116e,
	&node_u1167u1175,
	&node_u1169u1161,
	&node_u1169u1162,
	&node_u1169u1163,
	&node_u1169u1164,
	&node_u1169u1165,
	&node_u1169u1166,
	&node_u1169u1167,
	&node_u1169u1168,
	&node_u1169u1169,
	&node_u1169u116c,
	&node_u1169u116e,
	&node_u1169u1175,
	&node_u116au1175,
	&node_u116du1161,
	&node_u116du1162,
	&node_u116du1163,
	&node_u116du1164,
	&node_u116du1165,
	&node_u116du1167,
	&node_u116du1169,
	&node_u116du1175,
	&node_u116eu1161,
	&node_u116eu1162,
	&node_u116eu1165,
	&node_u116eu1166,
	&node_u116eu1167,
	&node_u116eu1168,
	&node_u116eu116e,
	&node_u116eu1175,
	&node_u116eu117c,
	&node_u116eud7c4,
	&node_u116fu1173,
	&node_u116fu1175,
	&node_u1171u1175,
	&node_u1172u1161,
	&node_u1172u1162,
	&node_u1172u1165,
	&node_u1172u1166,
	&node_u1172u1167,
	&node_u1172u1168,
	&node_u1172u1169,
	&node_u1172u116e,
	&node_u1172u1175,
	&node_u1173u1161,
	&node_u1173u1165,
	&node_u1173u1166,
	&node_u1173u1169,
	&node_u1173u116e,
	&node_u1173u1173,
	&node_u1173u1175,
	&node_u1173u119b,
	&node_u1174u116e,
	&node_u1175u1161,
	&node_u1175u1163,
	&node_u1175u1164,
	&node_u1175u1167,
	&node_u1175u1168,
	&node_u1175u1169,
	&node_u1175u116c,
	&node_u1175u116d,
	&node_u1175u116e,
	&node_u1175u1172,
	&node_u1175u1173,
	&node_u1175u1175,
	&node_u1175u1178,
	&node_u1175u119e,
	&node_u117fu1175,
	&node_u1182u1175,
	&node_u1184u1175,
	&node_u1189u1175,
	&node_u118fu1175,
	&node_u1191u1175,
	&node_u1199u1169,
	&node_u119au1175,
	&node_u119eu1161,
	&node_u119eu1165,
	&node_u119eu1166,
	&node_u119eu116e,
	&node_u119eu1175,
	&node_u119eu119e,
	&node_u11a8u11a8,
	&node_u11a8u11ab,
	&node_u11a8u11af,
	&node_u11a8u11b8,
	&node_u11a8u11ba,
	&node_u11a8u11be,
	&node_u11a8u11bf,
	&node_u11a8u11c2,
	&node_u11a8u11e7,
	&node_u11aau11a8,
	&node_u11abu11a8,
	&node_u11abu11ab,
	&node_u11abu11ae,
	&node_u11abu11af,
	&node_u11abu11ba,
	&node_u11abu11bd,
	&node_u11abu11be,
	&node_u11abu11c0,
	&node_u11abu11c2,
	&node_u11abu11eb,
	&node_u11aeu11a8,
	&node_u11aeu11ae,
	&node_u11aeu11af,
	&node_u11aeu11b8,
	&node_u11aeu11ba,
	&node_u11aeu11bd,
	&node_u11aeu11be,
	&node_u11aeu11c0,
	&node_u11aeu11e7,
	&node_u11aeud7cf,
	&node_u11afu11a8,
	&node_u11afu11a9,
	&node_u11afu11aa,
	&node_u11afu11ab,
	&node_u11afu11ae,
	&node_u11afu11af,
	&node_u11afu11b7,
	&node_u11afu11b8,
	&node_u11afu11b9,
	&node_u11afu11ba,
	&node_u11afu11bb,
	&node_u11afu11bc,
	&node_u11afu11bf,
	&node_u11afu11c0,
	&node_u11afu11c1,
	&node_u11afu11c2,
	&node_u11afu11d8,
	&node_u11afu11da,
	&node_u11afu11dd,
	&node_u11afu11e1,
	&node_u11afu11e4,
	&node_u11afu11e5,
	&node_u11afu11e6,
	&node_u11afu11eb,
	&node_u11afu11f0,
	&node_u11afu11f9,
	&node_u11afu11fe,
	&node_u11afud7e3,
	&node_u11b0u11a8,
	&node_u11b0u11ba,
	&node_u11b0u11c2,
	&node_u11b1u11a8,
	&node_u11b1u11ba,
	&node_u11b1u11c2,
	&node_u11b2u11ae,
	&node_u11b2u11ba,
	&node_u11b2u11bc,
	&node_u11b2u11c1,
	&node_u11b2u11c2,
	&node_u11b3u11ba,
	&node_u11b7u11a8,
	&node_u11b7u11ab,
	&node_u11b7u11af,
	&node_u11b7u11b7,
	&node_u11b7u11b8,
	&node_u11b7u11b9,
	&node_u11b7u11ba,
	&node_u11b7u11bb,
	&node_u11b7u11bc,
	&node_u11b7u11bd,
	&node_u11b7u11be,
	&node_u11b7u11c2,
	&node_u11b7u11eb,
	&node_u11b7u11ff,
	&node_u11b8u11ae,
	&node_u11b8u11af,
	&node_u11b8u11b5,
	&node_u11b8u11b7,
	&node_u11b8u11b8,
	&node_u11b8u11ba,
	&node_u11b8u11bc,
	&node_u11b8u11bd,
	&node_u11b8u11be,
	&node_u11b8u11c1,
	&node_u11b8u11c2,
	&node_u11b8u11e8,
	&node_u11b9u11ae,
	&node_u11bau11a8,
	&node_u11bau11ae,
	&node_u11bau11af,
	&node_u11bau11b7,
	&node_u11bau11b8,
	&node_u11bau11ba,
	&node_u11bau11bd,
	&node_u11bau11be,
	&node_u11bau11c0,
	&node_u11bau11c2,
	&node_u11bau11e6,
	&node_u11bau11e7,
	&node_u11bau11e8,
	&node_u11bau11eb,
	&node_u11bbu11a8,
	&node_u11bbu11ae,
	&node_u11bcu11a8,
	&node_u11bcu11a9,
	&node_u11bcu11bc,
	&node_u11bcu11bf,
	&node_u11bdu11b8,
	&node_u11bdu11bd,
	&node_u11bdud7e6,
	&node_u11c1u11b8,
	&node_u11c1u11ba,
	&node_u11c1u11bc,
	&node_u11c1u11c0,
	&node_u11c2u11ab,
	&node_u11c2u11af,
	&node_u11c2u11b7,
	&node_u11c2u11b8,
	&node_u11ceu11c2,
	&node_u11d0u11bf,
	&node_u11d9u11c2,
	&node_u11dcu11ba,
	&node_u11ddu11ba,
	&node_u11e3u11c1,
	&node_u11eau11bc,
	&node_u11ebu11b8,
	&node_u11ebu11e6,
	&node_u11ecu11a8,
	&node_u11f0u11a8,
	&node_u11f0u11a9,
	&node_u11f0u11b7,
	&node_u11f0u11ba,
	&node_u11f0u11bf,
	&node_u11f0u11c2,
	&node_u11f0u11eb,
	&node_u11f0u11f0,
	&node_ua964u1100,
	&node_ua966u1103,
	&node_ua969u1107,
	&node_ud7cdu11b8,
	&node_ud7d0u11a8,
	&node_ud7deu11ab,
	&node_ud7f3u11bc,
	&node_ud7f7u11b8,
	&node_u1105u1100u1100,
	&node_u1105u1103u1103,
	&node_u1105u1107u1107,
	&node_u1105u1107u110b,
	&node_u1107u1107u110b,
	&node_u1107u1109u1100,
	&node_u1107u1109u1103,
	&node_u1107u1109u1107,
	&node_u1107u1109u1109,
	&node_u1107u1109u110c,
	&node_u1107u1109u1110,
	&node_u1109u1107u1100,
	&node_u1109u1109u1107,
	&node_u1109u1109u1109,
	&node_u110cu110cu1112,
	&node_u1169u1161u1175,
	&node_u1169u1163u1175,
	&node_u1169u1165u1175,
	&node_u1169u1167u1175,
	&node_u1169u1169u1175,
	&node_u116du1161u1175,
	&node_u116du1163u1175,
	&node_u116eu1161u1175,
	&node_u116eu1165u1173,
	&node_u116eu1165u1175,
	&node_u116eu1167u1175,
	&node_u116eu1175u1175,
	&node_u1172u1161u1175,
	&node_u1172u1165u1175,
	&node_u1172u1167u1175,
	&node_u1173u1165u1175,
	&node_u1173u1175u116e,
	&node_u1175u1163u1169,
	&node_u1175u1163u1175,
	&node_u1175u1167u1175,
	&node_u1175u1169u1175,
	&node_u119eu1165u1175,
	&node_u11a8u11bau11a8,
	&node_u11aeu11aeu11b8,
	&node_u11aeu11bau11a8,
	&node_u11afu11a8u11a8,
	&node_u11afu11a8u11ba,
	&node_u11afu11a8u11c2,
	&node_u11afu11aeu11c2,
	&node_u11afu11afu11bf,
	&node_u11afu11b7u11a8,
	&node_u11afu11b7u11ba,
	&node_u11afu11b7u11c2,
	&node_u11afu11b8u11ae,
	&node_u11afu11b8u11ba,
	&node_u11afu11b8u11bc,
	&node_u11afu11b8u11c1,
	&node_u11afu11b8u11c2,
	&node_u11afu11bau11ba,
	&node_u11afu11f9u11c2,
	&node_u11b7u11abu11ab,
	&node_u11b7u11b8u11ba,
	&node_u11b7u11bau11ba,
	&node_u11b8u11afu11c1,
	&node_u11b8u11bau11ae,
	&node_u11bau11b8u11bc,
	&node_u11bau11bau11a8,
	&node_u11bau11bau11ae,
	&node_u11bcu11a8u11a8,
	&node_u11bdu11b8u11b8,
	&node_u11ebu11b8u11bc,
	&node_u11f0u11a8u11a8,
};
